/*
 * Swagger for Command BGE
 * Swagger API for FNT Command Business Gateway
 *
 * The version of the OpenAPI document: 20240226111547
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fntsoftware.businessgateway.entities;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ConfigurationDataConfigurationLayersResponseData
 */
@JsonPropertyOrder({
  ConfigurationDataConfigurationLayersResponseData.JSON_PROPERTY_LAYER_ELID,
  ConfigurationDataConfigurationLayersResponseData.JSON_PROPERTY_USE_VALIDITY_DATE,
  ConfigurationDataConfigurationLayersResponseData.JSON_PROPERTY_LAYER
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-26T11:20:24.990023935Z[Etc/UTC]")
public class ConfigurationDataConfigurationLayersResponseData {
  public static final String JSON_PROPERTY_LAYER_ELID = "layerElid";
  private String layerElid;

  public static final String JSON_PROPERTY_USE_VALIDITY_DATE = "useValidityDate";
  private Boolean useValidityDate;

  public static final String JSON_PROPERTY_LAYER = "layer";
  private String layer;

  public ConfigurationDataConfigurationLayersResponseData() {
  }

  public ConfigurationDataConfigurationLayersResponseData layerElid(String layerElid) {
    
    this.layerElid = layerElid;
    return this;
  }

   /**
   * Get layerElid
   * @return layerElid
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAYER_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLayerElid() {
    return layerElid;
  }


  @JsonProperty(JSON_PROPERTY_LAYER_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLayerElid(String layerElid) {
    this.layerElid = layerElid;
  }


  public ConfigurationDataConfigurationLayersResponseData useValidityDate(Boolean useValidityDate) {
    
    this.useValidityDate = useValidityDate;
    return this;
  }

   /**
   * Get useValidityDate
   * @return useValidityDate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USE_VALIDITY_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getUseValidityDate() {
    return useValidityDate;
  }


  @JsonProperty(JSON_PROPERTY_USE_VALIDITY_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUseValidityDate(Boolean useValidityDate) {
    this.useValidityDate = useValidityDate;
  }


  public ConfigurationDataConfigurationLayersResponseData layer(String layer) {
    
    this.layer = layer;
    return this;
  }

   /**
   * Get layer
   * @return layer
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAYER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLayer() {
    return layer;
  }


  @JsonProperty(JSON_PROPERTY_LAYER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLayer(String layer) {
    this.layer = layer;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigurationDataConfigurationLayersResponseData configurationDataConfigurationLayersResponseData = (ConfigurationDataConfigurationLayersResponseData) o;
    return Objects.equals(this.layerElid, configurationDataConfigurationLayersResponseData.layerElid) &&
        Objects.equals(this.useValidityDate, configurationDataConfigurationLayersResponseData.useValidityDate) &&
        Objects.equals(this.layer, configurationDataConfigurationLayersResponseData.layer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(layerElid, useValidityDate, layer);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigurationDataConfigurationLayersResponseData {\n");
    sb.append("    layerElid: ").append(toIndentedString(layerElid)).append("\n");
    sb.append("    useValidityDate: ").append(toIndentedString(useValidityDate)).append("\n");
    sb.append("    layer: ").append(toIndentedString(layer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

