/*
 * Swagger for Command BGE
 * Swagger API for FNT Command Business Gateway
 *
 * The version of the OpenAPI document: 20240131110751
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fntsoftware.businessgateway.entities;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fntsoftware.businessgateway.entities.RestrictionsBoolean;
import com.fntsoftware.businessgateway.entities.RestrictionsDate;
import com.fntsoftware.businessgateway.entities.RestrictionsNumeric;
import com.fntsoftware.businessgateway.entities.RestrictionsString;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * DeviceAllQueryExtendedRestriction
 */
@JsonPropertyOrder({
  DeviceAllQueryExtendedRestriction.JSON_PROPERTY_FLOOR_ELID,
  DeviceAllQueryExtendedRestriction.JSON_PROPERTY_ZONE_ELID,
  DeviceAllQueryExtendedRestriction.JSON_PROPERTY_POWER_CONSUMPTION_SPC,
  DeviceAllQueryExtendedRestriction.JSON_PROPERTY_PLAN_STATUS,
  DeviceAllQueryExtendedRestriction.JSON_PROPERTY_SYSTEM_RUNTIME,
  DeviceAllQueryExtendedRestriction.JSON_PROPERTY_WEIGHT_SPC,
  DeviceAllQueryExtendedRestriction.JSON_PROPERTY_CAMPUS_ELID,
  DeviceAllQueryExtendedRestriction.JSON_PROPERTY_REMARK,
  DeviceAllQueryExtendedRestriction.JSON_PROPERTY_EXPLANATION,
  DeviceAllQueryExtendedRestriction.JSON_PROPERTY_TYPE,
  DeviceAllQueryExtendedRestriction.JSON_PROPERTY_MANUFACTURER,
  DeviceAllQueryExtendedRestriction.JSON_PROPERTY_FUNCTION,
  DeviceAllQueryExtendedRestriction.JSON_PROPERTY_ROOM_ELID,
  DeviceAllQueryExtendedRestriction.JSON_PROPERTY_ID,
  DeviceAllQueryExtendedRestriction.JSON_PROPERTY_HEAT_EMISSION_SPC,
  DeviceAllQueryExtendedRestriction.JSON_PROPERTY_CLIMATE_RELEVANT,
  DeviceAllQueryExtendedRestriction.JSON_PROPERTY_POWER_CONSUMPTION,
  DeviceAllQueryExtendedRestriction.JSON_PROPERTY_POWER_SWITCHING_STATUS,
  DeviceAllQueryExtendedRestriction.JSON_PROPERTY_DIMENSION_WIDTH_SPC,
  DeviceAllQueryExtendedRestriction.JSON_PROPERTY_WEIGHT,
  DeviceAllQueryExtendedRestriction.JSON_PROPERTY_ENTITY_ID,
  DeviceAllQueryExtendedRestriction.JSON_PROPERTY_ELID,
  DeviceAllQueryExtendedRestriction.JSON_PROPERTY_DIMENSION_DEPTH_SPC,
  DeviceAllQueryExtendedRestriction.JSON_PROPERTY_DIMENSION_HEIGHT_SPC,
  DeviceAllQueryExtendedRestriction.JSON_PROPERTY_CLIMATE_CAPACITY_SPC,
  DeviceAllQueryExtendedRestriction.JSON_PROPERTY_LAST_SEEN,
  DeviceAllQueryExtendedRestriction.JSON_PROPERTY_TYPE_ELID,
  DeviceAllQueryExtendedRestriction.JSON_PROPERTY_TARGET_SUB_ENTITY,
  DeviceAllQueryExtendedRestriction.JSON_PROPERTY_VISIBLE_ID,
  DeviceAllQueryExtendedRestriction.JSON_PROPERTY_BUILDING_ELID,
  DeviceAllQueryExtendedRestriction.JSON_PROPERTY_HEAT_EMISSION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-31T11:10:37.320689708Z[Etc/UTC]")
public class DeviceAllQueryExtendedRestriction {
  public static final String JSON_PROPERTY_FLOOR_ELID = "floorElid";
  private RestrictionsString floorElid;

  public static final String JSON_PROPERTY_ZONE_ELID = "zoneElid";
  private RestrictionsString zoneElid;

  public static final String JSON_PROPERTY_POWER_CONSUMPTION_SPC = "powerConsumptionSpc";
  private RestrictionsNumeric powerConsumptionSpc;

  public static final String JSON_PROPERTY_PLAN_STATUS = "planStatus";
  private RestrictionsString planStatus;

  public static final String JSON_PROPERTY_SYSTEM_RUNTIME = "systemRuntime";
  private RestrictionsNumeric systemRuntime;

  public static final String JSON_PROPERTY_WEIGHT_SPC = "weightSpc";
  private RestrictionsNumeric weightSpc;

  public static final String JSON_PROPERTY_CAMPUS_ELID = "campusElid";
  private RestrictionsString campusElid;

  public static final String JSON_PROPERTY_REMARK = "remark";
  private RestrictionsString remark;

  public static final String JSON_PROPERTY_EXPLANATION = "explanation";
  private RestrictionsString explanation;

  public static final String JSON_PROPERTY_TYPE = "type";
  private RestrictionsString type;

  public static final String JSON_PROPERTY_MANUFACTURER = "manufacturer";
  private RestrictionsString manufacturer;

  public static final String JSON_PROPERTY_FUNCTION = "function";
  private RestrictionsString function;

  public static final String JSON_PROPERTY_ROOM_ELID = "roomElid";
  private RestrictionsString roomElid;

  public static final String JSON_PROPERTY_ID = "id";
  private RestrictionsString id;

  public static final String JSON_PROPERTY_HEAT_EMISSION_SPC = "heatEmissionSpc";
  private RestrictionsNumeric heatEmissionSpc;

  public static final String JSON_PROPERTY_CLIMATE_RELEVANT = "climateRelevant";
  private RestrictionsBoolean climateRelevant;

  public static final String JSON_PROPERTY_POWER_CONSUMPTION = "powerConsumption";
  private RestrictionsNumeric powerConsumption;

  public static final String JSON_PROPERTY_POWER_SWITCHING_STATUS = "powerSwitchingStatus";
  private RestrictionsString powerSwitchingStatus;

  public static final String JSON_PROPERTY_DIMENSION_WIDTH_SPC = "dimensionWidthSpc";
  private RestrictionsNumeric dimensionWidthSpc;

  public static final String JSON_PROPERTY_WEIGHT = "weight";
  private RestrictionsNumeric weight;

  public static final String JSON_PROPERTY_ENTITY_ID = "entityId";
  private RestrictionsString entityId;

  public static final String JSON_PROPERTY_ELID = "elid";
  private RestrictionsString elid;

  public static final String JSON_PROPERTY_DIMENSION_DEPTH_SPC = "dimensionDepthSpc";
  private RestrictionsNumeric dimensionDepthSpc;

  public static final String JSON_PROPERTY_DIMENSION_HEIGHT_SPC = "dimensionHeightSpc";
  private RestrictionsNumeric dimensionHeightSpc;

  public static final String JSON_PROPERTY_CLIMATE_CAPACITY_SPC = "climateCapacitySpc";
  private RestrictionsNumeric climateCapacitySpc;

  public static final String JSON_PROPERTY_LAST_SEEN = "lastSeen";
  private RestrictionsDate lastSeen;

  public static final String JSON_PROPERTY_TYPE_ELID = "typeElid";
  private RestrictionsString typeElid;

  public static final String JSON_PROPERTY_TARGET_SUB_ENTITY = "targetSubEntity";
  private RestrictionsString targetSubEntity;

  public static final String JSON_PROPERTY_VISIBLE_ID = "visibleId";
  private RestrictionsString visibleId;

  public static final String JSON_PROPERTY_BUILDING_ELID = "buildingElid";
  private RestrictionsString buildingElid;

  public static final String JSON_PROPERTY_HEAT_EMISSION = "heatEmission";
  private RestrictionsNumeric heatEmission;

  public DeviceAllQueryExtendedRestriction() {
  }

  public DeviceAllQueryExtendedRestriction floorElid(RestrictionsString floorElid) {
    
    this.floorElid = floorElid;
    return this;
  }

   /**
   * Get floorElid
   * @return floorElid
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FLOOR_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getFloorElid() {
    return floorElid;
  }


  @JsonProperty(JSON_PROPERTY_FLOOR_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFloorElid(RestrictionsString floorElid) {
    this.floorElid = floorElid;
  }


  public DeviceAllQueryExtendedRestriction zoneElid(RestrictionsString zoneElid) {
    
    this.zoneElid = zoneElid;
    return this;
  }

   /**
   * Get zoneElid
   * @return zoneElid
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ZONE_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getZoneElid() {
    return zoneElid;
  }


  @JsonProperty(JSON_PROPERTY_ZONE_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setZoneElid(RestrictionsString zoneElid) {
    this.zoneElid = zoneElid;
  }


  public DeviceAllQueryExtendedRestriction powerConsumptionSpc(RestrictionsNumeric powerConsumptionSpc) {
    
    this.powerConsumptionSpc = powerConsumptionSpc;
    return this;
  }

   /**
   * Get powerConsumptionSpc
   * @return powerConsumptionSpc
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POWER_CONSUMPTION_SPC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsNumeric getPowerConsumptionSpc() {
    return powerConsumptionSpc;
  }


  @JsonProperty(JSON_PROPERTY_POWER_CONSUMPTION_SPC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPowerConsumptionSpc(RestrictionsNumeric powerConsumptionSpc) {
    this.powerConsumptionSpc = powerConsumptionSpc;
  }


  public DeviceAllQueryExtendedRestriction planStatus(RestrictionsString planStatus) {
    
    this.planStatus = planStatus;
    return this;
  }

   /**
   * Get planStatus
   * @return planStatus
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PLAN_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getPlanStatus() {
    return planStatus;
  }


  @JsonProperty(JSON_PROPERTY_PLAN_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPlanStatus(RestrictionsString planStatus) {
    this.planStatus = planStatus;
  }


  public DeviceAllQueryExtendedRestriction systemRuntime(RestrictionsNumeric systemRuntime) {
    
    this.systemRuntime = systemRuntime;
    return this;
  }

   /**
   * Get systemRuntime
   * @return systemRuntime
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SYSTEM_RUNTIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsNumeric getSystemRuntime() {
    return systemRuntime;
  }


  @JsonProperty(JSON_PROPERTY_SYSTEM_RUNTIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSystemRuntime(RestrictionsNumeric systemRuntime) {
    this.systemRuntime = systemRuntime;
  }


  public DeviceAllQueryExtendedRestriction weightSpc(RestrictionsNumeric weightSpc) {
    
    this.weightSpc = weightSpc;
    return this;
  }

   /**
   * Get weightSpc
   * @return weightSpc
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WEIGHT_SPC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsNumeric getWeightSpc() {
    return weightSpc;
  }


  @JsonProperty(JSON_PROPERTY_WEIGHT_SPC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWeightSpc(RestrictionsNumeric weightSpc) {
    this.weightSpc = weightSpc;
  }


  public DeviceAllQueryExtendedRestriction campusElid(RestrictionsString campusElid) {
    
    this.campusElid = campusElid;
    return this;
  }

   /**
   * Get campusElid
   * @return campusElid
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CAMPUS_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getCampusElid() {
    return campusElid;
  }


  @JsonProperty(JSON_PROPERTY_CAMPUS_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCampusElid(RestrictionsString campusElid) {
    this.campusElid = campusElid;
  }


  public DeviceAllQueryExtendedRestriction remark(RestrictionsString remark) {
    
    this.remark = remark;
    return this;
  }

   /**
   * Get remark
   * @return remark
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REMARK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getRemark() {
    return remark;
  }


  @JsonProperty(JSON_PROPERTY_REMARK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRemark(RestrictionsString remark) {
    this.remark = remark;
  }


  public DeviceAllQueryExtendedRestriction explanation(RestrictionsString explanation) {
    
    this.explanation = explanation;
    return this;
  }

   /**
   * Get explanation
   * @return explanation
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPLANATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getExplanation() {
    return explanation;
  }


  @JsonProperty(JSON_PROPERTY_EXPLANATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExplanation(RestrictionsString explanation) {
    this.explanation = explanation;
  }


  public DeviceAllQueryExtendedRestriction type(RestrictionsString type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(RestrictionsString type) {
    this.type = type;
  }


  public DeviceAllQueryExtendedRestriction manufacturer(RestrictionsString manufacturer) {
    
    this.manufacturer = manufacturer;
    return this;
  }

   /**
   * Get manufacturer
   * @return manufacturer
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MANUFACTURER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getManufacturer() {
    return manufacturer;
  }


  @JsonProperty(JSON_PROPERTY_MANUFACTURER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManufacturer(RestrictionsString manufacturer) {
    this.manufacturer = manufacturer;
  }


  public DeviceAllQueryExtendedRestriction function(RestrictionsString function) {
    
    this.function = function;
    return this;
  }

   /**
   * Get function
   * @return function
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FUNCTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getFunction() {
    return function;
  }


  @JsonProperty(JSON_PROPERTY_FUNCTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFunction(RestrictionsString function) {
    this.function = function;
  }


  public DeviceAllQueryExtendedRestriction roomElid(RestrictionsString roomElid) {
    
    this.roomElid = roomElid;
    return this;
  }

   /**
   * Get roomElid
   * @return roomElid
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ROOM_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getRoomElid() {
    return roomElid;
  }


  @JsonProperty(JSON_PROPERTY_ROOM_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRoomElid(RestrictionsString roomElid) {
    this.roomElid = roomElid;
  }


  public DeviceAllQueryExtendedRestriction id(RestrictionsString id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(RestrictionsString id) {
    this.id = id;
  }


  public DeviceAllQueryExtendedRestriction heatEmissionSpc(RestrictionsNumeric heatEmissionSpc) {
    
    this.heatEmissionSpc = heatEmissionSpc;
    return this;
  }

   /**
   * Get heatEmissionSpc
   * @return heatEmissionSpc
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HEAT_EMISSION_SPC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsNumeric getHeatEmissionSpc() {
    return heatEmissionSpc;
  }


  @JsonProperty(JSON_PROPERTY_HEAT_EMISSION_SPC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeatEmissionSpc(RestrictionsNumeric heatEmissionSpc) {
    this.heatEmissionSpc = heatEmissionSpc;
  }


  public DeviceAllQueryExtendedRestriction climateRelevant(RestrictionsBoolean climateRelevant) {
    
    this.climateRelevant = climateRelevant;
    return this;
  }

   /**
   * Get climateRelevant
   * @return climateRelevant
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CLIMATE_RELEVANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsBoolean getClimateRelevant() {
    return climateRelevant;
  }


  @JsonProperty(JSON_PROPERTY_CLIMATE_RELEVANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClimateRelevant(RestrictionsBoolean climateRelevant) {
    this.climateRelevant = climateRelevant;
  }


  public DeviceAllQueryExtendedRestriction powerConsumption(RestrictionsNumeric powerConsumption) {
    
    this.powerConsumption = powerConsumption;
    return this;
  }

   /**
   * Get powerConsumption
   * @return powerConsumption
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POWER_CONSUMPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsNumeric getPowerConsumption() {
    return powerConsumption;
  }


  @JsonProperty(JSON_PROPERTY_POWER_CONSUMPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPowerConsumption(RestrictionsNumeric powerConsumption) {
    this.powerConsumption = powerConsumption;
  }


  public DeviceAllQueryExtendedRestriction powerSwitchingStatus(RestrictionsString powerSwitchingStatus) {
    
    this.powerSwitchingStatus = powerSwitchingStatus;
    return this;
  }

   /**
   * Get powerSwitchingStatus
   * @return powerSwitchingStatus
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POWER_SWITCHING_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getPowerSwitchingStatus() {
    return powerSwitchingStatus;
  }


  @JsonProperty(JSON_PROPERTY_POWER_SWITCHING_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPowerSwitchingStatus(RestrictionsString powerSwitchingStatus) {
    this.powerSwitchingStatus = powerSwitchingStatus;
  }


  public DeviceAllQueryExtendedRestriction dimensionWidthSpc(RestrictionsNumeric dimensionWidthSpc) {
    
    this.dimensionWidthSpc = dimensionWidthSpc;
    return this;
  }

   /**
   * Get dimensionWidthSpc
   * @return dimensionWidthSpc
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DIMENSION_WIDTH_SPC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsNumeric getDimensionWidthSpc() {
    return dimensionWidthSpc;
  }


  @JsonProperty(JSON_PROPERTY_DIMENSION_WIDTH_SPC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDimensionWidthSpc(RestrictionsNumeric dimensionWidthSpc) {
    this.dimensionWidthSpc = dimensionWidthSpc;
  }


  public DeviceAllQueryExtendedRestriction weight(RestrictionsNumeric weight) {
    
    this.weight = weight;
    return this;
  }

   /**
   * Get weight
   * @return weight
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsNumeric getWeight() {
    return weight;
  }


  @JsonProperty(JSON_PROPERTY_WEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWeight(RestrictionsNumeric weight) {
    this.weight = weight;
  }


  public DeviceAllQueryExtendedRestriction entityId(RestrictionsString entityId) {
    
    this.entityId = entityId;
    return this;
  }

   /**
   * Get entityId
   * @return entityId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENTITY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getEntityId() {
    return entityId;
  }


  @JsonProperty(JSON_PROPERTY_ENTITY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEntityId(RestrictionsString entityId) {
    this.entityId = entityId;
  }


  public DeviceAllQueryExtendedRestriction elid(RestrictionsString elid) {
    
    this.elid = elid;
    return this;
  }

   /**
   * Get elid
   * @return elid
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getElid() {
    return elid;
  }


  @JsonProperty(JSON_PROPERTY_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setElid(RestrictionsString elid) {
    this.elid = elid;
  }


  public DeviceAllQueryExtendedRestriction dimensionDepthSpc(RestrictionsNumeric dimensionDepthSpc) {
    
    this.dimensionDepthSpc = dimensionDepthSpc;
    return this;
  }

   /**
   * Get dimensionDepthSpc
   * @return dimensionDepthSpc
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DIMENSION_DEPTH_SPC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsNumeric getDimensionDepthSpc() {
    return dimensionDepthSpc;
  }


  @JsonProperty(JSON_PROPERTY_DIMENSION_DEPTH_SPC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDimensionDepthSpc(RestrictionsNumeric dimensionDepthSpc) {
    this.dimensionDepthSpc = dimensionDepthSpc;
  }


  public DeviceAllQueryExtendedRestriction dimensionHeightSpc(RestrictionsNumeric dimensionHeightSpc) {
    
    this.dimensionHeightSpc = dimensionHeightSpc;
    return this;
  }

   /**
   * Get dimensionHeightSpc
   * @return dimensionHeightSpc
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DIMENSION_HEIGHT_SPC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsNumeric getDimensionHeightSpc() {
    return dimensionHeightSpc;
  }


  @JsonProperty(JSON_PROPERTY_DIMENSION_HEIGHT_SPC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDimensionHeightSpc(RestrictionsNumeric dimensionHeightSpc) {
    this.dimensionHeightSpc = dimensionHeightSpc;
  }


  public DeviceAllQueryExtendedRestriction climateCapacitySpc(RestrictionsNumeric climateCapacitySpc) {
    
    this.climateCapacitySpc = climateCapacitySpc;
    return this;
  }

   /**
   * Get climateCapacitySpc
   * @return climateCapacitySpc
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CLIMATE_CAPACITY_SPC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsNumeric getClimateCapacitySpc() {
    return climateCapacitySpc;
  }


  @JsonProperty(JSON_PROPERTY_CLIMATE_CAPACITY_SPC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClimateCapacitySpc(RestrictionsNumeric climateCapacitySpc) {
    this.climateCapacitySpc = climateCapacitySpc;
  }


  public DeviceAllQueryExtendedRestriction lastSeen(RestrictionsDate lastSeen) {
    
    this.lastSeen = lastSeen;
    return this;
  }

   /**
   * Get lastSeen
   * @return lastSeen
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_SEEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsDate getLastSeen() {
    return lastSeen;
  }


  @JsonProperty(JSON_PROPERTY_LAST_SEEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastSeen(RestrictionsDate lastSeen) {
    this.lastSeen = lastSeen;
  }


  public DeviceAllQueryExtendedRestriction typeElid(RestrictionsString typeElid) {
    
    this.typeElid = typeElid;
    return this;
  }

   /**
   * Get typeElid
   * @return typeElid
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getTypeElid() {
    return typeElid;
  }


  @JsonProperty(JSON_PROPERTY_TYPE_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTypeElid(RestrictionsString typeElid) {
    this.typeElid = typeElid;
  }


  public DeviceAllQueryExtendedRestriction targetSubEntity(RestrictionsString targetSubEntity) {
    
    this.targetSubEntity = targetSubEntity;
    return this;
  }

   /**
   * Get targetSubEntity
   * @return targetSubEntity
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TARGET_SUB_ENTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getTargetSubEntity() {
    return targetSubEntity;
  }


  @JsonProperty(JSON_PROPERTY_TARGET_SUB_ENTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTargetSubEntity(RestrictionsString targetSubEntity) {
    this.targetSubEntity = targetSubEntity;
  }


  public DeviceAllQueryExtendedRestriction visibleId(RestrictionsString visibleId) {
    
    this.visibleId = visibleId;
    return this;
  }

   /**
   * Get visibleId
   * @return visibleId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VISIBLE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getVisibleId() {
    return visibleId;
  }


  @JsonProperty(JSON_PROPERTY_VISIBLE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVisibleId(RestrictionsString visibleId) {
    this.visibleId = visibleId;
  }


  public DeviceAllQueryExtendedRestriction buildingElid(RestrictionsString buildingElid) {
    
    this.buildingElid = buildingElid;
    return this;
  }

   /**
   * Get buildingElid
   * @return buildingElid
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BUILDING_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getBuildingElid() {
    return buildingElid;
  }


  @JsonProperty(JSON_PROPERTY_BUILDING_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBuildingElid(RestrictionsString buildingElid) {
    this.buildingElid = buildingElid;
  }


  public DeviceAllQueryExtendedRestriction heatEmission(RestrictionsNumeric heatEmission) {
    
    this.heatEmission = heatEmission;
    return this;
  }

   /**
   * Get heatEmission
   * @return heatEmission
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HEAT_EMISSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsNumeric getHeatEmission() {
    return heatEmission;
  }


  @JsonProperty(JSON_PROPERTY_HEAT_EMISSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeatEmission(RestrictionsNumeric heatEmission) {
    this.heatEmission = heatEmission;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceAllQueryExtendedRestriction deviceAllQueryExtendedRestriction = (DeviceAllQueryExtendedRestriction) o;
    return Objects.equals(this.floorElid, deviceAllQueryExtendedRestriction.floorElid) &&
        Objects.equals(this.zoneElid, deviceAllQueryExtendedRestriction.zoneElid) &&
        Objects.equals(this.powerConsumptionSpc, deviceAllQueryExtendedRestriction.powerConsumptionSpc) &&
        Objects.equals(this.planStatus, deviceAllQueryExtendedRestriction.planStatus) &&
        Objects.equals(this.systemRuntime, deviceAllQueryExtendedRestriction.systemRuntime) &&
        Objects.equals(this.weightSpc, deviceAllQueryExtendedRestriction.weightSpc) &&
        Objects.equals(this.campusElid, deviceAllQueryExtendedRestriction.campusElid) &&
        Objects.equals(this.remark, deviceAllQueryExtendedRestriction.remark) &&
        Objects.equals(this.explanation, deviceAllQueryExtendedRestriction.explanation) &&
        Objects.equals(this.type, deviceAllQueryExtendedRestriction.type) &&
        Objects.equals(this.manufacturer, deviceAllQueryExtendedRestriction.manufacturer) &&
        Objects.equals(this.function, deviceAllQueryExtendedRestriction.function) &&
        Objects.equals(this.roomElid, deviceAllQueryExtendedRestriction.roomElid) &&
        Objects.equals(this.id, deviceAllQueryExtendedRestriction.id) &&
        Objects.equals(this.heatEmissionSpc, deviceAllQueryExtendedRestriction.heatEmissionSpc) &&
        Objects.equals(this.climateRelevant, deviceAllQueryExtendedRestriction.climateRelevant) &&
        Objects.equals(this.powerConsumption, deviceAllQueryExtendedRestriction.powerConsumption) &&
        Objects.equals(this.powerSwitchingStatus, deviceAllQueryExtendedRestriction.powerSwitchingStatus) &&
        Objects.equals(this.dimensionWidthSpc, deviceAllQueryExtendedRestriction.dimensionWidthSpc) &&
        Objects.equals(this.weight, deviceAllQueryExtendedRestriction.weight) &&
        Objects.equals(this.entityId, deviceAllQueryExtendedRestriction.entityId) &&
        Objects.equals(this.elid, deviceAllQueryExtendedRestriction.elid) &&
        Objects.equals(this.dimensionDepthSpc, deviceAllQueryExtendedRestriction.dimensionDepthSpc) &&
        Objects.equals(this.dimensionHeightSpc, deviceAllQueryExtendedRestriction.dimensionHeightSpc) &&
        Objects.equals(this.climateCapacitySpc, deviceAllQueryExtendedRestriction.climateCapacitySpc) &&
        Objects.equals(this.lastSeen, deviceAllQueryExtendedRestriction.lastSeen) &&
        Objects.equals(this.typeElid, deviceAllQueryExtendedRestriction.typeElid) &&
        Objects.equals(this.targetSubEntity, deviceAllQueryExtendedRestriction.targetSubEntity) &&
        Objects.equals(this.visibleId, deviceAllQueryExtendedRestriction.visibleId) &&
        Objects.equals(this.buildingElid, deviceAllQueryExtendedRestriction.buildingElid) &&
        Objects.equals(this.heatEmission, deviceAllQueryExtendedRestriction.heatEmission);
  }

  @Override
  public int hashCode() {
    return Objects.hash(floorElid, zoneElid, powerConsumptionSpc, planStatus, systemRuntime, weightSpc, campusElid, remark, explanation, type, manufacturer, function, roomElid, id, heatEmissionSpc, climateRelevant, powerConsumption, powerSwitchingStatus, dimensionWidthSpc, weight, entityId, elid, dimensionDepthSpc, dimensionHeightSpc, climateCapacitySpc, lastSeen, typeElid, targetSubEntity, visibleId, buildingElid, heatEmission);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceAllQueryExtendedRestriction {\n");
    sb.append("    floorElid: ").append(toIndentedString(floorElid)).append("\n");
    sb.append("    zoneElid: ").append(toIndentedString(zoneElid)).append("\n");
    sb.append("    powerConsumptionSpc: ").append(toIndentedString(powerConsumptionSpc)).append("\n");
    sb.append("    planStatus: ").append(toIndentedString(planStatus)).append("\n");
    sb.append("    systemRuntime: ").append(toIndentedString(systemRuntime)).append("\n");
    sb.append("    weightSpc: ").append(toIndentedString(weightSpc)).append("\n");
    sb.append("    campusElid: ").append(toIndentedString(campusElid)).append("\n");
    sb.append("    remark: ").append(toIndentedString(remark)).append("\n");
    sb.append("    explanation: ").append(toIndentedString(explanation)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    manufacturer: ").append(toIndentedString(manufacturer)).append("\n");
    sb.append("    function: ").append(toIndentedString(function)).append("\n");
    sb.append("    roomElid: ").append(toIndentedString(roomElid)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    heatEmissionSpc: ").append(toIndentedString(heatEmissionSpc)).append("\n");
    sb.append("    climateRelevant: ").append(toIndentedString(climateRelevant)).append("\n");
    sb.append("    powerConsumption: ").append(toIndentedString(powerConsumption)).append("\n");
    sb.append("    powerSwitchingStatus: ").append(toIndentedString(powerSwitchingStatus)).append("\n");
    sb.append("    dimensionWidthSpc: ").append(toIndentedString(dimensionWidthSpc)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("    entityId: ").append(toIndentedString(entityId)).append("\n");
    sb.append("    elid: ").append(toIndentedString(elid)).append("\n");
    sb.append("    dimensionDepthSpc: ").append(toIndentedString(dimensionDepthSpc)).append("\n");
    sb.append("    dimensionHeightSpc: ").append(toIndentedString(dimensionHeightSpc)).append("\n");
    sb.append("    climateCapacitySpc: ").append(toIndentedString(climateCapacitySpc)).append("\n");
    sb.append("    lastSeen: ").append(toIndentedString(lastSeen)).append("\n");
    sb.append("    typeElid: ").append(toIndentedString(typeElid)).append("\n");
    sb.append("    targetSubEntity: ").append(toIndentedString(targetSubEntity)).append("\n");
    sb.append("    visibleId: ").append(toIndentedString(visibleId)).append("\n");
    sb.append("    buildingElid: ").append(toIndentedString(buildingElid)).append("\n");
    sb.append("    heatEmission: ").append(toIndentedString(heatEmission)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

