/*
 * Swagger for Command BGE
 * Swagger API for FNT Command Business Gateway
 *
 * The version of the OpenAPI document: 20240304133000
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fntsoftware.businessgateway.entities;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * HealthCheckShowTimeInfoResponseData
 */
@JsonPropertyOrder({
  HealthCheckShowTimeInfoResponseData.JSON_PROPERTY_DEFAULT_SHORT_UTC_AS_DATE,
  HealthCheckShowTimeInfoResponseData.JSON_PROPERTY_CURRENT_SHORT_UTC_AS_DATE,
  HealthCheckShowTimeInfoResponseData.JSON_PROPERTY_CURRENT_SHORT_UTC,
  HealthCheckShowTimeInfoResponseData.JSON_PROPERTY_CURRENT_TIMESTAMP,
  HealthCheckShowTimeInfoResponseData.JSON_PROPERTY_DEFAULT_SHORT_UTC,
  HealthCheckShowTimeInfoResponseData.JSON_PROPERTY_SYS_TIMESTAMP,
  HealthCheckShowTimeInfoResponseData.JSON_PROPERTY_DB_TIMEZONE,
  HealthCheckShowTimeInfoResponseData.JSON_PROPERTY_JAVA_TIME,
  HealthCheckShowTimeInfoResponseData.JSON_PROPERTY_SESSION_TIMEZONE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-04T13:31:32.601557352Z[Etc/UTC]")
public class HealthCheckShowTimeInfoResponseData {
  public static final String JSON_PROPERTY_DEFAULT_SHORT_UTC_AS_DATE = "defaultShortUtcAsDate";
  private String defaultShortUtcAsDate;

  public static final String JSON_PROPERTY_CURRENT_SHORT_UTC_AS_DATE = "currentShortUtcAsDate";
  private String currentShortUtcAsDate;

  public static final String JSON_PROPERTY_CURRENT_SHORT_UTC = "currentShortUtc";
  private String currentShortUtc;

  public static final String JSON_PROPERTY_CURRENT_TIMESTAMP = "currentTimestamp";
  private String currentTimestamp;

  public static final String JSON_PROPERTY_DEFAULT_SHORT_UTC = "defaultShortUtc";
  private String defaultShortUtc;

  public static final String JSON_PROPERTY_SYS_TIMESTAMP = "sysTimestamp";
  private String sysTimestamp;

  public static final String JSON_PROPERTY_DB_TIMEZONE = "dbTimezone";
  private String dbTimezone;

  public static final String JSON_PROPERTY_JAVA_TIME = "javaTime";
  private String javaTime;

  public static final String JSON_PROPERTY_SESSION_TIMEZONE = "sessionTimezone";
  private String sessionTimezone;

  public HealthCheckShowTimeInfoResponseData() {
  }

  public HealthCheckShowTimeInfoResponseData defaultShortUtcAsDate(String defaultShortUtcAsDate) {
    
    this.defaultShortUtcAsDate = defaultShortUtcAsDate;
    return this;
  }

   /**
   * Get defaultShortUtcAsDate
   * @return defaultShortUtcAsDate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEFAULT_SHORT_UTC_AS_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDefaultShortUtcAsDate() {
    return defaultShortUtcAsDate;
  }


  @JsonProperty(JSON_PROPERTY_DEFAULT_SHORT_UTC_AS_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefaultShortUtcAsDate(String defaultShortUtcAsDate) {
    this.defaultShortUtcAsDate = defaultShortUtcAsDate;
  }


  public HealthCheckShowTimeInfoResponseData currentShortUtcAsDate(String currentShortUtcAsDate) {
    
    this.currentShortUtcAsDate = currentShortUtcAsDate;
    return this;
  }

   /**
   * Get currentShortUtcAsDate
   * @return currentShortUtcAsDate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CURRENT_SHORT_UTC_AS_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCurrentShortUtcAsDate() {
    return currentShortUtcAsDate;
  }


  @JsonProperty(JSON_PROPERTY_CURRENT_SHORT_UTC_AS_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrentShortUtcAsDate(String currentShortUtcAsDate) {
    this.currentShortUtcAsDate = currentShortUtcAsDate;
  }


  public HealthCheckShowTimeInfoResponseData currentShortUtc(String currentShortUtc) {
    
    this.currentShortUtc = currentShortUtc;
    return this;
  }

   /**
   * Get currentShortUtc
   * @return currentShortUtc
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CURRENT_SHORT_UTC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCurrentShortUtc() {
    return currentShortUtc;
  }


  @JsonProperty(JSON_PROPERTY_CURRENT_SHORT_UTC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrentShortUtc(String currentShortUtc) {
    this.currentShortUtc = currentShortUtc;
  }


  public HealthCheckShowTimeInfoResponseData currentTimestamp(String currentTimestamp) {
    
    this.currentTimestamp = currentTimestamp;
    return this;
  }

   /**
   * Get currentTimestamp
   * @return currentTimestamp
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CURRENT_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCurrentTimestamp() {
    return currentTimestamp;
  }


  @JsonProperty(JSON_PROPERTY_CURRENT_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrentTimestamp(String currentTimestamp) {
    this.currentTimestamp = currentTimestamp;
  }


  public HealthCheckShowTimeInfoResponseData defaultShortUtc(String defaultShortUtc) {
    
    this.defaultShortUtc = defaultShortUtc;
    return this;
  }

   /**
   * Get defaultShortUtc
   * @return defaultShortUtc
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEFAULT_SHORT_UTC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDefaultShortUtc() {
    return defaultShortUtc;
  }


  @JsonProperty(JSON_PROPERTY_DEFAULT_SHORT_UTC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefaultShortUtc(String defaultShortUtc) {
    this.defaultShortUtc = defaultShortUtc;
  }


  public HealthCheckShowTimeInfoResponseData sysTimestamp(String sysTimestamp) {
    
    this.sysTimestamp = sysTimestamp;
    return this;
  }

   /**
   * Get sysTimestamp
   * @return sysTimestamp
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SYS_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSysTimestamp() {
    return sysTimestamp;
  }


  @JsonProperty(JSON_PROPERTY_SYS_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSysTimestamp(String sysTimestamp) {
    this.sysTimestamp = sysTimestamp;
  }


  public HealthCheckShowTimeInfoResponseData dbTimezone(String dbTimezone) {
    
    this.dbTimezone = dbTimezone;
    return this;
  }

   /**
   * Get dbTimezone
   * @return dbTimezone
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DB_TIMEZONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDbTimezone() {
    return dbTimezone;
  }


  @JsonProperty(JSON_PROPERTY_DB_TIMEZONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDbTimezone(String dbTimezone) {
    this.dbTimezone = dbTimezone;
  }


  public HealthCheckShowTimeInfoResponseData javaTime(String javaTime) {
    
    this.javaTime = javaTime;
    return this;
  }

   /**
   * Get javaTime
   * @return javaTime
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_JAVA_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getJavaTime() {
    return javaTime;
  }


  @JsonProperty(JSON_PROPERTY_JAVA_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setJavaTime(String javaTime) {
    this.javaTime = javaTime;
  }


  public HealthCheckShowTimeInfoResponseData sessionTimezone(String sessionTimezone) {
    
    this.sessionTimezone = sessionTimezone;
    return this;
  }

   /**
   * Get sessionTimezone
   * @return sessionTimezone
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SESSION_TIMEZONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSessionTimezone() {
    return sessionTimezone;
  }


  @JsonProperty(JSON_PROPERTY_SESSION_TIMEZONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSessionTimezone(String sessionTimezone) {
    this.sessionTimezone = sessionTimezone;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HealthCheckShowTimeInfoResponseData healthCheckShowTimeInfoResponseData = (HealthCheckShowTimeInfoResponseData) o;
    return Objects.equals(this.defaultShortUtcAsDate, healthCheckShowTimeInfoResponseData.defaultShortUtcAsDate) &&
        Objects.equals(this.currentShortUtcAsDate, healthCheckShowTimeInfoResponseData.currentShortUtcAsDate) &&
        Objects.equals(this.currentShortUtc, healthCheckShowTimeInfoResponseData.currentShortUtc) &&
        Objects.equals(this.currentTimestamp, healthCheckShowTimeInfoResponseData.currentTimestamp) &&
        Objects.equals(this.defaultShortUtc, healthCheckShowTimeInfoResponseData.defaultShortUtc) &&
        Objects.equals(this.sysTimestamp, healthCheckShowTimeInfoResponseData.sysTimestamp) &&
        Objects.equals(this.dbTimezone, healthCheckShowTimeInfoResponseData.dbTimezone) &&
        Objects.equals(this.javaTime, healthCheckShowTimeInfoResponseData.javaTime) &&
        Objects.equals(this.sessionTimezone, healthCheckShowTimeInfoResponseData.sessionTimezone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(defaultShortUtcAsDate, currentShortUtcAsDate, currentShortUtc, currentTimestamp, defaultShortUtc, sysTimestamp, dbTimezone, javaTime, sessionTimezone);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HealthCheckShowTimeInfoResponseData {\n");
    sb.append("    defaultShortUtcAsDate: ").append(toIndentedString(defaultShortUtcAsDate)).append("\n");
    sb.append("    currentShortUtcAsDate: ").append(toIndentedString(currentShortUtcAsDate)).append("\n");
    sb.append("    currentShortUtc: ").append(toIndentedString(currentShortUtc)).append("\n");
    sb.append("    currentTimestamp: ").append(toIndentedString(currentTimestamp)).append("\n");
    sb.append("    defaultShortUtc: ").append(toIndentedString(defaultShortUtc)).append("\n");
    sb.append("    sysTimestamp: ").append(toIndentedString(sysTimestamp)).append("\n");
    sb.append("    dbTimezone: ").append(toIndentedString(dbTimezone)).append("\n");
    sb.append("    javaTime: ").append(toIndentedString(javaTime)).append("\n");
    sb.append("    sessionTimezone: ").append(toIndentedString(sessionTimezone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

