/*
 * Swagger for Command BGE
 * Swagger API for FNT Command Business Gateway
 *
 * The version of the OpenAPI document: 20240131110751
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fntsoftware.businessgateway.entities;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import org.joda.time.DateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * JobMasterMonitoringInformationResponseData
 */
@JsonPropertyOrder({
  JobMasterMonitoringInformationResponseData.JSON_PROPERTY_JOB_NAME,
  JobMasterMonitoringInformationResponseData.JSON_PROPERTY_GROUP_NAME,
  JobMasterMonitoringInformationResponseData.JSON_PROPERTY_DESCRIPTION,
  JobMasterMonitoringInformationResponseData.JSON_PROPERTY_END,
  JobMasterMonitoringInformationResponseData.JSON_PROPERTY_USER_NAME,
  JobMasterMonitoringInformationResponseData.JSON_PROPERTY_BEGIN,
  JobMasterMonitoringInformationResponseData.JSON_PROPERTY_MONITORING_ID,
  JobMasterMonitoringInformationResponseData.JSON_PROPERTY_STATUS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-31T11:10:37.320689708Z[Etc/UTC]")
public class JobMasterMonitoringInformationResponseData {
  public static final String JSON_PROPERTY_JOB_NAME = "jobName";
  private String jobName;

  public static final String JSON_PROPERTY_GROUP_NAME = "groupName";
  private String groupName;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_END = "end";
  private DateTime end;

  public static final String JSON_PROPERTY_USER_NAME = "userName";
  private String userName;

  public static final String JSON_PROPERTY_BEGIN = "begin";
  private DateTime begin;

  public static final String JSON_PROPERTY_MONITORING_ID = "monitoringId";
  private BigDecimal monitoringId;

  public static final String JSON_PROPERTY_STATUS = "status";
  private String status;

  public JobMasterMonitoringInformationResponseData() {
  }

  public JobMasterMonitoringInformationResponseData jobName(String jobName) {
    
    this.jobName = jobName;
    return this;
  }

   /**
   * Get jobName
   * @return jobName
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_JOB_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getJobName() {
    return jobName;
  }


  @JsonProperty(JSON_PROPERTY_JOB_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setJobName(String jobName) {
    this.jobName = jobName;
  }


  public JobMasterMonitoringInformationResponseData groupName(String groupName) {
    
    this.groupName = groupName;
    return this;
  }

   /**
   * Get groupName
   * @return groupName
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GROUP_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGroupName() {
    return groupName;
  }


  @JsonProperty(JSON_PROPERTY_GROUP_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGroupName(String groupName) {
    this.groupName = groupName;
  }


  public JobMasterMonitoringInformationResponseData description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }


  public JobMasterMonitoringInformationResponseData end(DateTime end) {
    
    this.end = end;
    return this;
  }

   /**
   * Get end
   * @return end
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_END)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DateTime getEnd() {
    return end;
  }


  @JsonProperty(JSON_PROPERTY_END)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnd(DateTime end) {
    this.end = end;
  }


  public JobMasterMonitoringInformationResponseData userName(String userName) {
    
    this.userName = userName;
    return this;
  }

   /**
   * Get userName
   * @return userName
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUserName() {
    return userName;
  }


  @JsonProperty(JSON_PROPERTY_USER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserName(String userName) {
    this.userName = userName;
  }


  public JobMasterMonitoringInformationResponseData begin(DateTime begin) {
    
    this.begin = begin;
    return this;
  }

   /**
   * Get begin
   * @return begin
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BEGIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DateTime getBegin() {
    return begin;
  }


  @JsonProperty(JSON_PROPERTY_BEGIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBegin(DateTime begin) {
    this.begin = begin;
  }


  public JobMasterMonitoringInformationResponseData monitoringId(BigDecimal monitoringId) {
    
    this.monitoringId = monitoringId;
    return this;
  }

   /**
   * Get monitoringId
   * @return monitoringId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MONITORING_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getMonitoringId() {
    return monitoringId;
  }


  @JsonProperty(JSON_PROPERTY_MONITORING_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMonitoringId(BigDecimal monitoringId) {
    this.monitoringId = monitoringId;
  }


  public JobMasterMonitoringInformationResponseData status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobMasterMonitoringInformationResponseData jobMasterMonitoringInformationResponseData = (JobMasterMonitoringInformationResponseData) o;
    return Objects.equals(this.jobName, jobMasterMonitoringInformationResponseData.jobName) &&
        Objects.equals(this.groupName, jobMasterMonitoringInformationResponseData.groupName) &&
        Objects.equals(this.description, jobMasterMonitoringInformationResponseData.description) &&
        Objects.equals(this.end, jobMasterMonitoringInformationResponseData.end) &&
        Objects.equals(this.userName, jobMasterMonitoringInformationResponseData.userName) &&
        Objects.equals(this.begin, jobMasterMonitoringInformationResponseData.begin) &&
        Objects.equals(this.monitoringId, jobMasterMonitoringInformationResponseData.monitoringId) &&
        Objects.equals(this.status, jobMasterMonitoringInformationResponseData.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(jobName, groupName, description, end, userName, begin, monitoringId, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobMasterMonitoringInformationResponseData {\n");
    sb.append("    jobName: ").append(toIndentedString(jobName)).append("\n");
    sb.append("    groupName: ").append(toIndentedString(groupName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    end: ").append(toIndentedString(end)).append("\n");
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    begin: ").append(toIndentedString(begin)).append("\n");
    sb.append("    monitoringId: ").append(toIndentedString(monitoringId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

