/*
 * Swagger for Command BGE
 * Swagger API for FNT Command Business Gateway
 *
 * The version of the OpenAPI document: 20240226111547
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fntsoftware.businessgateway.entities;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * NodeTypeData
 */
@JsonPropertyOrder({
  NodeTypeData.JSON_PROPERTY_DISPLAY_IN_NAVIGATOR,
  NodeTypeData.JSON_PROPERTY_IS_STANDARD,
  NodeTypeData.JSON_PROPERTY_DESCRIPTION,
  NodeTypeData.JSON_PROPERTY_ID_PREFIX,
  NodeTypeData.JSON_PROPERTY_PLACE_OBJECTS,
  NodeTypeData.JSON_PROPERTY_TYPE,
  NodeTypeData.JSON_PROPERTY_ELID,
  NodeTypeData.JSON_PROPERTY_GRAPHICAL_NODE,
  NodeTypeData.JSON_PROPERTY_MANUFACTURER
})
@JsonTypeName("nodeTypeData")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-26T11:20:24.990023935Z[Etc/UTC]")
public class NodeTypeData {
  public static final String JSON_PROPERTY_DISPLAY_IN_NAVIGATOR = "displayInNavigator";
  private Boolean displayInNavigator;

  public static final String JSON_PROPERTY_IS_STANDARD = "isStandard";
  private Boolean isStandard;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_ID_PREFIX = "idPrefix";
  private String idPrefix;

  public static final String JSON_PROPERTY_PLACE_OBJECTS = "placeObjects";
  private Boolean placeObjects;

  public static final String JSON_PROPERTY_TYPE = "type";
  private String type;

  public static final String JSON_PROPERTY_ELID = "elid";
  private String elid;

  public static final String JSON_PROPERTY_GRAPHICAL_NODE = "graphicalNode";
  private String graphicalNode;

  public static final String JSON_PROPERTY_MANUFACTURER = "manufacturer";
  private String manufacturer;

  public NodeTypeData() {
  }

  public NodeTypeData displayInNavigator(Boolean displayInNavigator) {
    
    this.displayInNavigator = displayInNavigator;
    return this;
  }

   /**
   * Get displayInNavigator
   * @return displayInNavigator
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISPLAY_IN_NAVIGATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDisplayInNavigator() {
    return displayInNavigator;
  }


  @JsonProperty(JSON_PROPERTY_DISPLAY_IN_NAVIGATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisplayInNavigator(Boolean displayInNavigator) {
    this.displayInNavigator = displayInNavigator;
  }


  public NodeTypeData isStandard(Boolean isStandard) {
    
    this.isStandard = isStandard;
    return this;
  }

   /**
   * Get isStandard
   * @return isStandard
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_STANDARD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsStandard() {
    return isStandard;
  }


  @JsonProperty(JSON_PROPERTY_IS_STANDARD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsStandard(Boolean isStandard) {
    this.isStandard = isStandard;
  }


  public NodeTypeData description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }


  public NodeTypeData idPrefix(String idPrefix) {
    
    this.idPrefix = idPrefix;
    return this;
  }

   /**
   * Get idPrefix
   * @return idPrefix
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID_PREFIX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIdPrefix() {
    return idPrefix;
  }


  @JsonProperty(JSON_PROPERTY_ID_PREFIX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdPrefix(String idPrefix) {
    this.idPrefix = idPrefix;
  }


  public NodeTypeData placeObjects(Boolean placeObjects) {
    
    this.placeObjects = placeObjects;
    return this;
  }

   /**
   * Get placeObjects
   * @return placeObjects
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PLACE_OBJECTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPlaceObjects() {
    return placeObjects;
  }


  @JsonProperty(JSON_PROPERTY_PLACE_OBJECTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPlaceObjects(Boolean placeObjects) {
    this.placeObjects = placeObjects;
  }


  public NodeTypeData type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(String type) {
    this.type = type;
  }


  public NodeTypeData elid(String elid) {
    
    this.elid = elid;
    return this;
  }

   /**
   * Get elid
   * @return elid
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getElid() {
    return elid;
  }


  @JsonProperty(JSON_PROPERTY_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setElid(String elid) {
    this.elid = elid;
  }


  public NodeTypeData graphicalNode(String graphicalNode) {
    
    this.graphicalNode = graphicalNode;
    return this;
  }

   /**
   * Get graphicalNode
   * @return graphicalNode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GRAPHICAL_NODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGraphicalNode() {
    return graphicalNode;
  }


  @JsonProperty(JSON_PROPERTY_GRAPHICAL_NODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGraphicalNode(String graphicalNode) {
    this.graphicalNode = graphicalNode;
  }


  public NodeTypeData manufacturer(String manufacturer) {
    
    this.manufacturer = manufacturer;
    return this;
  }

   /**
   * Get manufacturer
   * @return manufacturer
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MANUFACTURER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getManufacturer() {
    return manufacturer;
  }


  @JsonProperty(JSON_PROPERTY_MANUFACTURER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManufacturer(String manufacturer) {
    this.manufacturer = manufacturer;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NodeTypeData nodeTypeData = (NodeTypeData) o;
    return Objects.equals(this.displayInNavigator, nodeTypeData.displayInNavigator) &&
        Objects.equals(this.isStandard, nodeTypeData.isStandard) &&
        Objects.equals(this.description, nodeTypeData.description) &&
        Objects.equals(this.idPrefix, nodeTypeData.idPrefix) &&
        Objects.equals(this.placeObjects, nodeTypeData.placeObjects) &&
        Objects.equals(this.type, nodeTypeData.type) &&
        Objects.equals(this.elid, nodeTypeData.elid) &&
        Objects.equals(this.graphicalNode, nodeTypeData.graphicalNode) &&
        Objects.equals(this.manufacturer, nodeTypeData.manufacturer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayInNavigator, isStandard, description, idPrefix, placeObjects, type, elid, graphicalNode, manufacturer);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NodeTypeData {\n");
    sb.append("    displayInNavigator: ").append(toIndentedString(displayInNavigator)).append("\n");
    sb.append("    isStandard: ").append(toIndentedString(isStandard)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    idPrefix: ").append(toIndentedString(idPrefix)).append("\n");
    sb.append("    placeObjects: ").append(toIndentedString(placeObjects)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    elid: ").append(toIndentedString(elid)).append("\n");
    sb.append("    graphicalNode: ").append(toIndentedString(graphicalNode)).append("\n");
    sb.append("    manufacturer: ").append(toIndentedString(manufacturer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

