/*
 * Swagger for Command BGE
 * Swagger API for FNT Command Business Gateway
 *
 * The version of the OpenAPI document: 20240131110751
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fntsoftware.businessgateway.entities;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fntsoftware.businessgateway.entities.RestrictionsBoolean;
import com.fntsoftware.businessgateway.entities.RestrictionsDate;
import com.fntsoftware.businessgateway.entities.RestrictionsNumeric;
import com.fntsoftware.businessgateway.entities.RestrictionsString;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PersonSoftwareLicensesEntityRestriction
 */
@JsonPropertyOrder({
  PersonSoftwareLicensesEntityRestriction.JSON_PROPERTY_DEFAULT_USAGE,
  PersonSoftwareLicensesEntityRestriction.JSON_PROPERTY_LICENCE_KEY,
  PersonSoftwareLicensesEntityRestriction.JSON_PROPERTY_SOFTWARE_BASE_ELID,
  PersonSoftwareLicensesEntityRestriction.JSON_PROPERTY_LICENCE_AMOUNT,
  PersonSoftwareLicensesEntityRestriction.JSON_PROPERTY_LICENCE_TYPE,
  PersonSoftwareLicensesEntityRestriction.JSON_PROPERTY_SUPPLIER,
  PersonSoftwareLicensesEntityRestriction.JSON_PROPERTY_LICENCE_UNLIMITED,
  PersonSoftwareLicensesEntityRestriction.JSON_PROPERTY_VALID_UNTIL,
  PersonSoftwareLicensesEntityRestriction.JSON_PROPERTY_ID,
  PersonSoftwareLicensesEntityRestriction.JSON_PROPERTY_VALID_FROM,
  PersonSoftwareLicensesEntityRestriction.JSON_PROPERTY_ELID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-31T11:10:37.320689708Z[Etc/UTC]")
public class PersonSoftwareLicensesEntityRestriction {
  public static final String JSON_PROPERTY_DEFAULT_USAGE = "defaultUsage";
  private RestrictionsNumeric defaultUsage;

  public static final String JSON_PROPERTY_LICENCE_KEY = "licenceKey";
  private RestrictionsString licenceKey;

  public static final String JSON_PROPERTY_SOFTWARE_BASE_ELID = "softwareBaseElid";
  private RestrictionsString softwareBaseElid;

  public static final String JSON_PROPERTY_LICENCE_AMOUNT = "licenceAmount";
  private RestrictionsNumeric licenceAmount;

  public static final String JSON_PROPERTY_LICENCE_TYPE = "licenceType";
  private RestrictionsString licenceType;

  public static final String JSON_PROPERTY_SUPPLIER = "supplier";
  private RestrictionsString supplier;

  public static final String JSON_PROPERTY_LICENCE_UNLIMITED = "licenceUnlimited";
  private RestrictionsBoolean licenceUnlimited;

  public static final String JSON_PROPERTY_VALID_UNTIL = "validUntil";
  private RestrictionsDate validUntil;

  public static final String JSON_PROPERTY_ID = "id";
  private RestrictionsString id;

  public static final String JSON_PROPERTY_VALID_FROM = "validFrom";
  private RestrictionsDate validFrom;

  public static final String JSON_PROPERTY_ELID = "elid";
  private RestrictionsString elid;

  public PersonSoftwareLicensesEntityRestriction() {
  }

  public PersonSoftwareLicensesEntityRestriction defaultUsage(RestrictionsNumeric defaultUsage) {
    
    this.defaultUsage = defaultUsage;
    return this;
  }

   /**
   * Get defaultUsage
   * @return defaultUsage
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEFAULT_USAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsNumeric getDefaultUsage() {
    return defaultUsage;
  }


  @JsonProperty(JSON_PROPERTY_DEFAULT_USAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefaultUsage(RestrictionsNumeric defaultUsage) {
    this.defaultUsage = defaultUsage;
  }


  public PersonSoftwareLicensesEntityRestriction licenceKey(RestrictionsString licenceKey) {
    
    this.licenceKey = licenceKey;
    return this;
  }

   /**
   * Get licenceKey
   * @return licenceKey
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LICENCE_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getLicenceKey() {
    return licenceKey;
  }


  @JsonProperty(JSON_PROPERTY_LICENCE_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLicenceKey(RestrictionsString licenceKey) {
    this.licenceKey = licenceKey;
  }


  public PersonSoftwareLicensesEntityRestriction softwareBaseElid(RestrictionsString softwareBaseElid) {
    
    this.softwareBaseElid = softwareBaseElid;
    return this;
  }

   /**
   * Get softwareBaseElid
   * @return softwareBaseElid
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SOFTWARE_BASE_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getSoftwareBaseElid() {
    return softwareBaseElid;
  }


  @JsonProperty(JSON_PROPERTY_SOFTWARE_BASE_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSoftwareBaseElid(RestrictionsString softwareBaseElid) {
    this.softwareBaseElid = softwareBaseElid;
  }


  public PersonSoftwareLicensesEntityRestriction licenceAmount(RestrictionsNumeric licenceAmount) {
    
    this.licenceAmount = licenceAmount;
    return this;
  }

   /**
   * Get licenceAmount
   * @return licenceAmount
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LICENCE_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsNumeric getLicenceAmount() {
    return licenceAmount;
  }


  @JsonProperty(JSON_PROPERTY_LICENCE_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLicenceAmount(RestrictionsNumeric licenceAmount) {
    this.licenceAmount = licenceAmount;
  }


  public PersonSoftwareLicensesEntityRestriction licenceType(RestrictionsString licenceType) {
    
    this.licenceType = licenceType;
    return this;
  }

   /**
   * Get licenceType
   * @return licenceType
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LICENCE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getLicenceType() {
    return licenceType;
  }


  @JsonProperty(JSON_PROPERTY_LICENCE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLicenceType(RestrictionsString licenceType) {
    this.licenceType = licenceType;
  }


  public PersonSoftwareLicensesEntityRestriction supplier(RestrictionsString supplier) {
    
    this.supplier = supplier;
    return this;
  }

   /**
   * Get supplier
   * @return supplier
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUPPLIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getSupplier() {
    return supplier;
  }


  @JsonProperty(JSON_PROPERTY_SUPPLIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSupplier(RestrictionsString supplier) {
    this.supplier = supplier;
  }


  public PersonSoftwareLicensesEntityRestriction licenceUnlimited(RestrictionsBoolean licenceUnlimited) {
    
    this.licenceUnlimited = licenceUnlimited;
    return this;
  }

   /**
   * Get licenceUnlimited
   * @return licenceUnlimited
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LICENCE_UNLIMITED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsBoolean getLicenceUnlimited() {
    return licenceUnlimited;
  }


  @JsonProperty(JSON_PROPERTY_LICENCE_UNLIMITED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLicenceUnlimited(RestrictionsBoolean licenceUnlimited) {
    this.licenceUnlimited = licenceUnlimited;
  }


  public PersonSoftwareLicensesEntityRestriction validUntil(RestrictionsDate validUntil) {
    
    this.validUntil = validUntil;
    return this;
  }

   /**
   * Get validUntil
   * @return validUntil
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALID_UNTIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsDate getValidUntil() {
    return validUntil;
  }


  @JsonProperty(JSON_PROPERTY_VALID_UNTIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValidUntil(RestrictionsDate validUntil) {
    this.validUntil = validUntil;
  }


  public PersonSoftwareLicensesEntityRestriction id(RestrictionsString id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(RestrictionsString id) {
    this.id = id;
  }


  public PersonSoftwareLicensesEntityRestriction validFrom(RestrictionsDate validFrom) {
    
    this.validFrom = validFrom;
    return this;
  }

   /**
   * Get validFrom
   * @return validFrom
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALID_FROM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsDate getValidFrom() {
    return validFrom;
  }


  @JsonProperty(JSON_PROPERTY_VALID_FROM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValidFrom(RestrictionsDate validFrom) {
    this.validFrom = validFrom;
  }


  public PersonSoftwareLicensesEntityRestriction elid(RestrictionsString elid) {
    
    this.elid = elid;
    return this;
  }

   /**
   * Get elid
   * @return elid
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getElid() {
    return elid;
  }


  @JsonProperty(JSON_PROPERTY_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setElid(RestrictionsString elid) {
    this.elid = elid;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PersonSoftwareLicensesEntityRestriction personSoftwareLicensesEntityRestriction = (PersonSoftwareLicensesEntityRestriction) o;
    return Objects.equals(this.defaultUsage, personSoftwareLicensesEntityRestriction.defaultUsage) &&
        Objects.equals(this.licenceKey, personSoftwareLicensesEntityRestriction.licenceKey) &&
        Objects.equals(this.softwareBaseElid, personSoftwareLicensesEntityRestriction.softwareBaseElid) &&
        Objects.equals(this.licenceAmount, personSoftwareLicensesEntityRestriction.licenceAmount) &&
        Objects.equals(this.licenceType, personSoftwareLicensesEntityRestriction.licenceType) &&
        Objects.equals(this.supplier, personSoftwareLicensesEntityRestriction.supplier) &&
        Objects.equals(this.licenceUnlimited, personSoftwareLicensesEntityRestriction.licenceUnlimited) &&
        Objects.equals(this.validUntil, personSoftwareLicensesEntityRestriction.validUntil) &&
        Objects.equals(this.id, personSoftwareLicensesEntityRestriction.id) &&
        Objects.equals(this.validFrom, personSoftwareLicensesEntityRestriction.validFrom) &&
        Objects.equals(this.elid, personSoftwareLicensesEntityRestriction.elid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(defaultUsage, licenceKey, softwareBaseElid, licenceAmount, licenceType, supplier, licenceUnlimited, validUntil, id, validFrom, elid);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PersonSoftwareLicensesEntityRestriction {\n");
    sb.append("    defaultUsage: ").append(toIndentedString(defaultUsage)).append("\n");
    sb.append("    licenceKey: ").append(toIndentedString(licenceKey)).append("\n");
    sb.append("    softwareBaseElid: ").append(toIndentedString(softwareBaseElid)).append("\n");
    sb.append("    licenceAmount: ").append(toIndentedString(licenceAmount)).append("\n");
    sb.append("    licenceType: ").append(toIndentedString(licenceType)).append("\n");
    sb.append("    supplier: ").append(toIndentedString(supplier)).append("\n");
    sb.append("    licenceUnlimited: ").append(toIndentedString(licenceUnlimited)).append("\n");
    sb.append("    validUntil: ").append(toIndentedString(validUntil)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    validFrom: ").append(toIndentedString(validFrom)).append("\n");
    sb.append("    elid: ").append(toIndentedString(elid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

