/*
 * Swagger for Command BGE
 * Swagger API for FNT Command Business Gateway
 *
 * The version of the OpenAPI document: 20240304133000
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fntsoftware.businessgateway.entities;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fntsoftware.businessgateway.entities.PlaceAssemblyUnitInCabinetDeviceAllCreateLinkSwitchCabinetRequestData;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PlaceAssemblyUnitInCabinetDeviceAllRequestData
 */
@JsonPropertyOrder({
  PlaceAssemblyUnitInCabinetDeviceAllRequestData.JSON_PROPERTY_COLLECTION_MAIN_ELID,
  PlaceAssemblyUnitInCabinetDeviceAllRequestData.JSON_PROPERTY_CREATE_LINK_SWITCH_CABINET
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-04T13:31:32.601557352Z[Etc/UTC]")
public class PlaceAssemblyUnitInCabinetDeviceAllRequestData {
  public static final String JSON_PROPERTY_COLLECTION_MAIN_ELID = "collectionMainElid";
  private String collectionMainElid;

  public static final String JSON_PROPERTY_CREATE_LINK_SWITCH_CABINET = "createLinkSwitchCabinet";
  private PlaceAssemblyUnitInCabinetDeviceAllCreateLinkSwitchCabinetRequestData createLinkSwitchCabinet;

  public PlaceAssemblyUnitInCabinetDeviceAllRequestData() {
  }

  public PlaceAssemblyUnitInCabinetDeviceAllRequestData collectionMainElid(String collectionMainElid) {
    
    this.collectionMainElid = collectionMainElid;
    return this;
  }

   /**
   * Get collectionMainElid
   * @return collectionMainElid
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COLLECTION_MAIN_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCollectionMainElid() {
    return collectionMainElid;
  }


  @JsonProperty(JSON_PROPERTY_COLLECTION_MAIN_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCollectionMainElid(String collectionMainElid) {
    this.collectionMainElid = collectionMainElid;
  }


  public PlaceAssemblyUnitInCabinetDeviceAllRequestData createLinkSwitchCabinet(PlaceAssemblyUnitInCabinetDeviceAllCreateLinkSwitchCabinetRequestData createLinkSwitchCabinet) {
    
    this.createLinkSwitchCabinet = createLinkSwitchCabinet;
    return this;
  }

   /**
   * Get createLinkSwitchCabinet
   * @return createLinkSwitchCabinet
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATE_LINK_SWITCH_CABINET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public PlaceAssemblyUnitInCabinetDeviceAllCreateLinkSwitchCabinetRequestData getCreateLinkSwitchCabinet() {
    return createLinkSwitchCabinet;
  }


  @JsonProperty(JSON_PROPERTY_CREATE_LINK_SWITCH_CABINET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreateLinkSwitchCabinet(PlaceAssemblyUnitInCabinetDeviceAllCreateLinkSwitchCabinetRequestData createLinkSwitchCabinet) {
    this.createLinkSwitchCabinet = createLinkSwitchCabinet;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlaceAssemblyUnitInCabinetDeviceAllRequestData placeAssemblyUnitInCabinetDeviceAllRequestData = (PlaceAssemblyUnitInCabinetDeviceAllRequestData) o;
    return Objects.equals(this.collectionMainElid, placeAssemblyUnitInCabinetDeviceAllRequestData.collectionMainElid) &&
        Objects.equals(this.createLinkSwitchCabinet, placeAssemblyUnitInCabinetDeviceAllRequestData.createLinkSwitchCabinet);
  }

  @Override
  public int hashCode() {
    return Objects.hash(collectionMainElid, createLinkSwitchCabinet);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlaceAssemblyUnitInCabinetDeviceAllRequestData {\n");
    sb.append("    collectionMainElid: ").append(toIndentedString(collectionMainElid)).append("\n");
    sb.append("    createLinkSwitchCabinet: ").append(toIndentedString(createLinkSwitchCabinet)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

