/*
 * Swagger for Command BGE
 * Swagger API for FNT Command Business Gateway
 *
 * The version of the OpenAPI document: 20240226111547
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fntsoftware.businessgateway.entities;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fntsoftware.businessgateway.entities.DataCableData;
import com.fntsoftware.businessgateway.entities.ServiceTelcoConcatenatedPathCustomDataCablesRelation;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ServiceTelcoConcatenatedPathCustomDataCablesData
 */
@JsonPropertyOrder({
  ServiceTelcoConcatenatedPathCustomDataCablesData.JSON_PROPERTY_ENTITY,
  ServiceTelcoConcatenatedPathCustomDataCablesData.JSON_PROPERTY_RELATION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-26T11:20:24.990023935Z[Etc/UTC]")
public class ServiceTelcoConcatenatedPathCustomDataCablesData {
  public static final String JSON_PROPERTY_ENTITY = "entity";
  private DataCableData entity;

  public static final String JSON_PROPERTY_RELATION = "relation";
  private ServiceTelcoConcatenatedPathCustomDataCablesRelation relation;

  public ServiceTelcoConcatenatedPathCustomDataCablesData() {
  }

  public ServiceTelcoConcatenatedPathCustomDataCablesData entity(DataCableData entity) {
    
    this.entity = entity;
    return this;
  }

   /**
   * Get entity
   * @return entity
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DataCableData getEntity() {
    return entity;
  }


  @JsonProperty(JSON_PROPERTY_ENTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEntity(DataCableData entity) {
    this.entity = entity;
  }


  public ServiceTelcoConcatenatedPathCustomDataCablesData relation(ServiceTelcoConcatenatedPathCustomDataCablesRelation relation) {
    
    this.relation = relation;
    return this;
  }

   /**
   * Get relation
   * @return relation
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RELATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ServiceTelcoConcatenatedPathCustomDataCablesRelation getRelation() {
    return relation;
  }


  @JsonProperty(JSON_PROPERTY_RELATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRelation(ServiceTelcoConcatenatedPathCustomDataCablesRelation relation) {
    this.relation = relation;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceTelcoConcatenatedPathCustomDataCablesData serviceTelcoConcatenatedPathCustomDataCablesData = (ServiceTelcoConcatenatedPathCustomDataCablesData) o;
    return Objects.equals(this.entity, serviceTelcoConcatenatedPathCustomDataCablesData.entity) &&
        Objects.equals(this.relation, serviceTelcoConcatenatedPathCustomDataCablesData.relation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entity, relation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceTelcoConcatenatedPathCustomDataCablesData {\n");
    sb.append("    entity: ").append(toIndentedString(entity)).append("\n");
    sb.append("    relation: ").append(toIndentedString(relation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

