/*
 * Swagger for Command BGE
 * Swagger API for FNT Command Business Gateway
 *
 * The version of the OpenAPI document: 20240226111547
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fntsoftware.businessgateway.entities;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ServiceTelcoPathStructuresResponseData
 */
@JsonPropertyOrder({
  ServiceTelcoPathStructuresResponseData.JSON_PROPERTY_LOCK_FLAG,
  ServiceTelcoPathStructuresResponseData.JSON_PROPERTY_PROVIDED_RESOURCE,
  ServiceTelcoPathStructuresResponseData.JSON_PROPERTY_RESOURCE_ID,
  ServiceTelcoPathStructuresResponseData.JSON_PROPERTY_SERVICE_RX_ELID,
  ServiceTelcoPathStructuresResponseData.JSON_PROPERTY_SERVICE_TX_ELID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-26T11:20:24.990023935Z[Etc/UTC]")
public class ServiceTelcoPathStructuresResponseData {
  public static final String JSON_PROPERTY_LOCK_FLAG = "lockFlag";
  private Boolean lockFlag;

  public static final String JSON_PROPERTY_PROVIDED_RESOURCE = "providedResource";
  private String providedResource;

  public static final String JSON_PROPERTY_RESOURCE_ID = "resourceId";
  private String resourceId;

  public static final String JSON_PROPERTY_SERVICE_RX_ELID = "serviceRxElid";
  private String serviceRxElid;

  public static final String JSON_PROPERTY_SERVICE_TX_ELID = "serviceTxElid";
  private String serviceTxElid;

  public ServiceTelcoPathStructuresResponseData() {
  }

  public ServiceTelcoPathStructuresResponseData lockFlag(Boolean lockFlag) {
    
    this.lockFlag = lockFlag;
    return this;
  }

   /**
   * Get lockFlag
   * @return lockFlag
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCK_FLAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getLockFlag() {
    return lockFlag;
  }


  @JsonProperty(JSON_PROPERTY_LOCK_FLAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLockFlag(Boolean lockFlag) {
    this.lockFlag = lockFlag;
  }


  public ServiceTelcoPathStructuresResponseData providedResource(String providedResource) {
    
    this.providedResource = providedResource;
    return this;
  }

   /**
   * Get providedResource
   * @return providedResource
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROVIDED_RESOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProvidedResource() {
    return providedResource;
  }


  @JsonProperty(JSON_PROPERTY_PROVIDED_RESOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProvidedResource(String providedResource) {
    this.providedResource = providedResource;
  }


  public ServiceTelcoPathStructuresResponseData resourceId(String resourceId) {
    
    this.resourceId = resourceId;
    return this;
  }

   /**
   * Get resourceId
   * @return resourceId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESOURCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getResourceId() {
    return resourceId;
  }


  @JsonProperty(JSON_PROPERTY_RESOURCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResourceId(String resourceId) {
    this.resourceId = resourceId;
  }


  public ServiceTelcoPathStructuresResponseData serviceRxElid(String serviceRxElid) {
    
    this.serviceRxElid = serviceRxElid;
    return this;
  }

   /**
   * Get serviceRxElid
   * @return serviceRxElid
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SERVICE_RX_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getServiceRxElid() {
    return serviceRxElid;
  }


  @JsonProperty(JSON_PROPERTY_SERVICE_RX_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServiceRxElid(String serviceRxElid) {
    this.serviceRxElid = serviceRxElid;
  }


  public ServiceTelcoPathStructuresResponseData serviceTxElid(String serviceTxElid) {
    
    this.serviceTxElid = serviceTxElid;
    return this;
  }

   /**
   * Get serviceTxElid
   * @return serviceTxElid
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SERVICE_TX_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getServiceTxElid() {
    return serviceTxElid;
  }


  @JsonProperty(JSON_PROPERTY_SERVICE_TX_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServiceTxElid(String serviceTxElid) {
    this.serviceTxElid = serviceTxElid;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceTelcoPathStructuresResponseData serviceTelcoPathStructuresResponseData = (ServiceTelcoPathStructuresResponseData) o;
    return Objects.equals(this.lockFlag, serviceTelcoPathStructuresResponseData.lockFlag) &&
        Objects.equals(this.providedResource, serviceTelcoPathStructuresResponseData.providedResource) &&
        Objects.equals(this.resourceId, serviceTelcoPathStructuresResponseData.resourceId) &&
        Objects.equals(this.serviceRxElid, serviceTelcoPathStructuresResponseData.serviceRxElid) &&
        Objects.equals(this.serviceTxElid, serviceTelcoPathStructuresResponseData.serviceTxElid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lockFlag, providedResource, resourceId, serviceRxElid, serviceTxElid);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceTelcoPathStructuresResponseData {\n");
    sb.append("    lockFlag: ").append(toIndentedString(lockFlag)).append("\n");
    sb.append("    providedResource: ").append(toIndentedString(providedResource)).append("\n");
    sb.append("    resourceId: ").append(toIndentedString(resourceId)).append("\n");
    sb.append("    serviceRxElid: ").append(toIndentedString(serviceRxElid)).append("\n");
    sb.append("    serviceTxElid: ").append(toIndentedString(serviceTxElid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

