/*
 * Swagger for Command BGE
 * Swagger API for FNT Command Business Gateway
 *
 * The version of the OpenAPI document: 20240226111547
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fntsoftware.businessgateway.entities;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fntsoftware.businessgateway.entities.RestrictionsBoolean;
import com.fntsoftware.businessgateway.entities.RestrictionsDate;
import com.fntsoftware.businessgateway.entities.RestrictionsString;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction
 */
@JsonPropertyOrder({
  SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.JSON_PROPERTY_MAINTENANCE_INTERVAL,
  SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.JSON_PROPERTY_END_DATE,
  SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.JSON_PROPERTY_LIFETIME,
  SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.JSON_PROPERTY_DESCRIPTION,
  SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.JSON_PROPERTY_C_DISMISSAL_DATE,
  SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.JSON_PROPERTY_C_AUTOMATIC_RENEWAL,
  SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.JSON_PROPERTY_C_DISMISSAL_RECEIVED_DATE,
  SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.JSON_PROPERTY_C_REFTYPE1,
  SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.JSON_PROPERTY_DISMISSAL_PROTECTION,
  SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.JSON_PROPERTY_NEXT_MAINTENANCE_DATE,
  SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.JSON_PROPERTY_C_REFVALUE1,
  SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.JSON_PROPERTY_C_REFVALUE2,
  SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.JSON_PROPERTY_ID,
  SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.JSON_PROPERTY_C_REFTYPE2,
  SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.JSON_PROPERTY_C_DISMISSAL_PROTECTION_END,
  SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.JSON_PROPERTY_LAST_MAINTENANCE_DATE,
  SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.JSON_PROPERTY_MAINTENANCE_PARTNER,
  SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.JSON_PROPERTY_C_AUTO_RENEWAL_PERIOD,
  SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.JSON_PROPERTY_C_SUPPORT_SVC_SW,
  SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.JSON_PROPERTY_C_RENEWAL_DATE,
  SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.JSON_PROPERTY_RUNTIME,
  SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.JSON_PROPERTY_C_SUPPORT_TIME_SW,
  SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.JSON_PROPERTY_C_SUPPORT_REACTION_HW,
  SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.JSON_PROPERTY_DISTRIBUTOR,
  SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.JSON_PROPERTY_ELID,
  SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.JSON_PROPERTY_C_SUPPORT_REACTION_SW,
  SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.JSON_PROPERTY_BEGIN_DATE,
  SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.JSON_PROPERTY_DISMISSAL,
  SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.JSON_PROPERTY_C_DISMISSAL_END_DATE,
  SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.JSON_PROPERTY_C_SUPPORT_SVC_HW,
  SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.JSON_PROPERTY_C_RENEWAL,
  SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.JSON_PROPERTY_C_SUPPORT_TIME_HW
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-26T11:20:24.990023935Z[Etc/UTC]")
public class SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction {
  public static final String JSON_PROPERTY_MAINTENANCE_INTERVAL = "maintenanceInterval";
  private RestrictionsString maintenanceInterval;

  public static final String JSON_PROPERTY_END_DATE = "endDate";
  private RestrictionsDate endDate;

  public static final String JSON_PROPERTY_LIFETIME = "lifetime";
  private RestrictionsBoolean lifetime;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private RestrictionsString description;

  public static final String JSON_PROPERTY_C_DISMISSAL_DATE = "cDismissalDate";
  private RestrictionsDate cDismissalDate;

  public static final String JSON_PROPERTY_C_AUTOMATIC_RENEWAL = "cAutomaticRenewal";
  private RestrictionsString cAutomaticRenewal;

  public static final String JSON_PROPERTY_C_DISMISSAL_RECEIVED_DATE = "cDismissalReceivedDate";
  private RestrictionsDate cDismissalReceivedDate;

  public static final String JSON_PROPERTY_C_REFTYPE1 = "cReftype1";
  private RestrictionsString cReftype1;

  public static final String JSON_PROPERTY_DISMISSAL_PROTECTION = "dismissalProtection";
  private RestrictionsString dismissalProtection;

  public static final String JSON_PROPERTY_NEXT_MAINTENANCE_DATE = "nextMaintenanceDate";
  private RestrictionsDate nextMaintenanceDate;

  public static final String JSON_PROPERTY_C_REFVALUE1 = "cRefvalue1";
  private RestrictionsString cRefvalue1;

  public static final String JSON_PROPERTY_C_REFVALUE2 = "cRefvalue2";
  private RestrictionsString cRefvalue2;

  public static final String JSON_PROPERTY_ID = "id";
  private RestrictionsString id;

  public static final String JSON_PROPERTY_C_REFTYPE2 = "cReftype2";
  private RestrictionsString cReftype2;

  public static final String JSON_PROPERTY_C_DISMISSAL_PROTECTION_END = "cDismissalProtectionEnd";
  private RestrictionsDate cDismissalProtectionEnd;

  public static final String JSON_PROPERTY_LAST_MAINTENANCE_DATE = "lastMaintenanceDate";
  private RestrictionsDate lastMaintenanceDate;

  public static final String JSON_PROPERTY_MAINTENANCE_PARTNER = "maintenancePartner";
  private RestrictionsString maintenancePartner;

  public static final String JSON_PROPERTY_C_AUTO_RENEWAL_PERIOD = "cAutoRenewalPeriod";
  private RestrictionsString cAutoRenewalPeriod;

  public static final String JSON_PROPERTY_C_SUPPORT_SVC_SW = "cSupportSvcSw";
  private RestrictionsString cSupportSvcSw;

  public static final String JSON_PROPERTY_C_RENEWAL_DATE = "cRenewalDate";
  private RestrictionsDate cRenewalDate;

  public static final String JSON_PROPERTY_RUNTIME = "runtime";
  private RestrictionsString runtime;

  public static final String JSON_PROPERTY_C_SUPPORT_TIME_SW = "cSupportTimeSw";
  private RestrictionsString cSupportTimeSw;

  public static final String JSON_PROPERTY_C_SUPPORT_REACTION_HW = "cSupportReactionHw";
  private RestrictionsString cSupportReactionHw;

  public static final String JSON_PROPERTY_DISTRIBUTOR = "distributor";
  private RestrictionsString distributor;

  public static final String JSON_PROPERTY_ELID = "elid";
  private RestrictionsString elid;

  public static final String JSON_PROPERTY_C_SUPPORT_REACTION_SW = "cSupportReactionSw";
  private RestrictionsString cSupportReactionSw;

  public static final String JSON_PROPERTY_BEGIN_DATE = "beginDate";
  private RestrictionsDate beginDate;

  public static final String JSON_PROPERTY_DISMISSAL = "dismissal";
  private RestrictionsString dismissal;

  public static final String JSON_PROPERTY_C_DISMISSAL_END_DATE = "cDismissalEndDate";
  private RestrictionsDate cDismissalEndDate;

  public static final String JSON_PROPERTY_C_SUPPORT_SVC_HW = "cSupportSvcHw";
  private RestrictionsString cSupportSvcHw;

  public static final String JSON_PROPERTY_C_RENEWAL = "cRenewal";
  private RestrictionsString cRenewal;

  public static final String JSON_PROPERTY_C_SUPPORT_TIME_HW = "cSupportTimeHw";
  private RestrictionsString cSupportTimeHw;

  public SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction() {
  }

  public SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction maintenanceInterval(RestrictionsString maintenanceInterval) {
    
    this.maintenanceInterval = maintenanceInterval;
    return this;
  }

   /**
   * Get maintenanceInterval
   * @return maintenanceInterval
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MAINTENANCE_INTERVAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getMaintenanceInterval() {
    return maintenanceInterval;
  }


  @JsonProperty(JSON_PROPERTY_MAINTENANCE_INTERVAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaintenanceInterval(RestrictionsString maintenanceInterval) {
    this.maintenanceInterval = maintenanceInterval;
  }


  public SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction endDate(RestrictionsDate endDate) {
    
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_END_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsDate getEndDate() {
    return endDate;
  }


  @JsonProperty(JSON_PROPERTY_END_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndDate(RestrictionsDate endDate) {
    this.endDate = endDate;
  }


  public SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction lifetime(RestrictionsBoolean lifetime) {
    
    this.lifetime = lifetime;
    return this;
  }

   /**
   * Get lifetime
   * @return lifetime
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LIFETIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsBoolean getLifetime() {
    return lifetime;
  }


  @JsonProperty(JSON_PROPERTY_LIFETIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLifetime(RestrictionsBoolean lifetime) {
    this.lifetime = lifetime;
  }


  public SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction description(RestrictionsString description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(RestrictionsString description) {
    this.description = description;
  }


  public SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction cDismissalDate(RestrictionsDate cDismissalDate) {
    
    this.cDismissalDate = cDismissalDate;
    return this;
  }

   /**
   * Get cDismissalDate
   * @return cDismissalDate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_C_DISMISSAL_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsDate getcDismissalDate() {
    return cDismissalDate;
  }


  @JsonProperty(JSON_PROPERTY_C_DISMISSAL_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setcDismissalDate(RestrictionsDate cDismissalDate) {
    this.cDismissalDate = cDismissalDate;
  }


  public SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction cAutomaticRenewal(RestrictionsString cAutomaticRenewal) {
    
    this.cAutomaticRenewal = cAutomaticRenewal;
    return this;
  }

   /**
   * Get cAutomaticRenewal
   * @return cAutomaticRenewal
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_C_AUTOMATIC_RENEWAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getcAutomaticRenewal() {
    return cAutomaticRenewal;
  }


  @JsonProperty(JSON_PROPERTY_C_AUTOMATIC_RENEWAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setcAutomaticRenewal(RestrictionsString cAutomaticRenewal) {
    this.cAutomaticRenewal = cAutomaticRenewal;
  }


  public SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction cDismissalReceivedDate(RestrictionsDate cDismissalReceivedDate) {
    
    this.cDismissalReceivedDate = cDismissalReceivedDate;
    return this;
  }

   /**
   * Get cDismissalReceivedDate
   * @return cDismissalReceivedDate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_C_DISMISSAL_RECEIVED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsDate getcDismissalReceivedDate() {
    return cDismissalReceivedDate;
  }


  @JsonProperty(JSON_PROPERTY_C_DISMISSAL_RECEIVED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setcDismissalReceivedDate(RestrictionsDate cDismissalReceivedDate) {
    this.cDismissalReceivedDate = cDismissalReceivedDate;
  }


  public SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction cReftype1(RestrictionsString cReftype1) {
    
    this.cReftype1 = cReftype1;
    return this;
  }

   /**
   * Get cReftype1
   * @return cReftype1
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_C_REFTYPE1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getcReftype1() {
    return cReftype1;
  }


  @JsonProperty(JSON_PROPERTY_C_REFTYPE1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setcReftype1(RestrictionsString cReftype1) {
    this.cReftype1 = cReftype1;
  }


  public SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction dismissalProtection(RestrictionsString dismissalProtection) {
    
    this.dismissalProtection = dismissalProtection;
    return this;
  }

   /**
   * Get dismissalProtection
   * @return dismissalProtection
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISMISSAL_PROTECTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getDismissalProtection() {
    return dismissalProtection;
  }


  @JsonProperty(JSON_PROPERTY_DISMISSAL_PROTECTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDismissalProtection(RestrictionsString dismissalProtection) {
    this.dismissalProtection = dismissalProtection;
  }


  public SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction nextMaintenanceDate(RestrictionsDate nextMaintenanceDate) {
    
    this.nextMaintenanceDate = nextMaintenanceDate;
    return this;
  }

   /**
   * Get nextMaintenanceDate
   * @return nextMaintenanceDate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NEXT_MAINTENANCE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsDate getNextMaintenanceDate() {
    return nextMaintenanceDate;
  }


  @JsonProperty(JSON_PROPERTY_NEXT_MAINTENANCE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNextMaintenanceDate(RestrictionsDate nextMaintenanceDate) {
    this.nextMaintenanceDate = nextMaintenanceDate;
  }


  public SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction cRefvalue1(RestrictionsString cRefvalue1) {
    
    this.cRefvalue1 = cRefvalue1;
    return this;
  }

   /**
   * Get cRefvalue1
   * @return cRefvalue1
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_C_REFVALUE1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getcRefvalue1() {
    return cRefvalue1;
  }


  @JsonProperty(JSON_PROPERTY_C_REFVALUE1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setcRefvalue1(RestrictionsString cRefvalue1) {
    this.cRefvalue1 = cRefvalue1;
  }


  public SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction cRefvalue2(RestrictionsString cRefvalue2) {
    
    this.cRefvalue2 = cRefvalue2;
    return this;
  }

   /**
   * Get cRefvalue2
   * @return cRefvalue2
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_C_REFVALUE2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getcRefvalue2() {
    return cRefvalue2;
  }


  @JsonProperty(JSON_PROPERTY_C_REFVALUE2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setcRefvalue2(RestrictionsString cRefvalue2) {
    this.cRefvalue2 = cRefvalue2;
  }


  public SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction id(RestrictionsString id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(RestrictionsString id) {
    this.id = id;
  }


  public SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction cReftype2(RestrictionsString cReftype2) {
    
    this.cReftype2 = cReftype2;
    return this;
  }

   /**
   * Get cReftype2
   * @return cReftype2
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_C_REFTYPE2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getcReftype2() {
    return cReftype2;
  }


  @JsonProperty(JSON_PROPERTY_C_REFTYPE2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setcReftype2(RestrictionsString cReftype2) {
    this.cReftype2 = cReftype2;
  }


  public SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction cDismissalProtectionEnd(RestrictionsDate cDismissalProtectionEnd) {
    
    this.cDismissalProtectionEnd = cDismissalProtectionEnd;
    return this;
  }

   /**
   * Get cDismissalProtectionEnd
   * @return cDismissalProtectionEnd
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_C_DISMISSAL_PROTECTION_END)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsDate getcDismissalProtectionEnd() {
    return cDismissalProtectionEnd;
  }


  @JsonProperty(JSON_PROPERTY_C_DISMISSAL_PROTECTION_END)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setcDismissalProtectionEnd(RestrictionsDate cDismissalProtectionEnd) {
    this.cDismissalProtectionEnd = cDismissalProtectionEnd;
  }


  public SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction lastMaintenanceDate(RestrictionsDate lastMaintenanceDate) {
    
    this.lastMaintenanceDate = lastMaintenanceDate;
    return this;
  }

   /**
   * Get lastMaintenanceDate
   * @return lastMaintenanceDate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_MAINTENANCE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsDate getLastMaintenanceDate() {
    return lastMaintenanceDate;
  }


  @JsonProperty(JSON_PROPERTY_LAST_MAINTENANCE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastMaintenanceDate(RestrictionsDate lastMaintenanceDate) {
    this.lastMaintenanceDate = lastMaintenanceDate;
  }


  public SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction maintenancePartner(RestrictionsString maintenancePartner) {
    
    this.maintenancePartner = maintenancePartner;
    return this;
  }

   /**
   * Get maintenancePartner
   * @return maintenancePartner
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MAINTENANCE_PARTNER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getMaintenancePartner() {
    return maintenancePartner;
  }


  @JsonProperty(JSON_PROPERTY_MAINTENANCE_PARTNER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaintenancePartner(RestrictionsString maintenancePartner) {
    this.maintenancePartner = maintenancePartner;
  }


  public SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction cAutoRenewalPeriod(RestrictionsString cAutoRenewalPeriod) {
    
    this.cAutoRenewalPeriod = cAutoRenewalPeriod;
    return this;
  }

   /**
   * Get cAutoRenewalPeriod
   * @return cAutoRenewalPeriod
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_C_AUTO_RENEWAL_PERIOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getcAutoRenewalPeriod() {
    return cAutoRenewalPeriod;
  }


  @JsonProperty(JSON_PROPERTY_C_AUTO_RENEWAL_PERIOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setcAutoRenewalPeriod(RestrictionsString cAutoRenewalPeriod) {
    this.cAutoRenewalPeriod = cAutoRenewalPeriod;
  }


  public SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction cSupportSvcSw(RestrictionsString cSupportSvcSw) {
    
    this.cSupportSvcSw = cSupportSvcSw;
    return this;
  }

   /**
   * Get cSupportSvcSw
   * @return cSupportSvcSw
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_C_SUPPORT_SVC_SW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getcSupportSvcSw() {
    return cSupportSvcSw;
  }


  @JsonProperty(JSON_PROPERTY_C_SUPPORT_SVC_SW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setcSupportSvcSw(RestrictionsString cSupportSvcSw) {
    this.cSupportSvcSw = cSupportSvcSw;
  }


  public SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction cRenewalDate(RestrictionsDate cRenewalDate) {
    
    this.cRenewalDate = cRenewalDate;
    return this;
  }

   /**
   * Get cRenewalDate
   * @return cRenewalDate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_C_RENEWAL_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsDate getcRenewalDate() {
    return cRenewalDate;
  }


  @JsonProperty(JSON_PROPERTY_C_RENEWAL_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setcRenewalDate(RestrictionsDate cRenewalDate) {
    this.cRenewalDate = cRenewalDate;
  }


  public SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction runtime(RestrictionsString runtime) {
    
    this.runtime = runtime;
    return this;
  }

   /**
   * Get runtime
   * @return runtime
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RUNTIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getRuntime() {
    return runtime;
  }


  @JsonProperty(JSON_PROPERTY_RUNTIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRuntime(RestrictionsString runtime) {
    this.runtime = runtime;
  }


  public SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction cSupportTimeSw(RestrictionsString cSupportTimeSw) {
    
    this.cSupportTimeSw = cSupportTimeSw;
    return this;
  }

   /**
   * Get cSupportTimeSw
   * @return cSupportTimeSw
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_C_SUPPORT_TIME_SW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getcSupportTimeSw() {
    return cSupportTimeSw;
  }


  @JsonProperty(JSON_PROPERTY_C_SUPPORT_TIME_SW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setcSupportTimeSw(RestrictionsString cSupportTimeSw) {
    this.cSupportTimeSw = cSupportTimeSw;
  }


  public SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction cSupportReactionHw(RestrictionsString cSupportReactionHw) {
    
    this.cSupportReactionHw = cSupportReactionHw;
    return this;
  }

   /**
   * Get cSupportReactionHw
   * @return cSupportReactionHw
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_C_SUPPORT_REACTION_HW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getcSupportReactionHw() {
    return cSupportReactionHw;
  }


  @JsonProperty(JSON_PROPERTY_C_SUPPORT_REACTION_HW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setcSupportReactionHw(RestrictionsString cSupportReactionHw) {
    this.cSupportReactionHw = cSupportReactionHw;
  }


  public SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction distributor(RestrictionsString distributor) {
    
    this.distributor = distributor;
    return this;
  }

   /**
   * Get distributor
   * @return distributor
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISTRIBUTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getDistributor() {
    return distributor;
  }


  @JsonProperty(JSON_PROPERTY_DISTRIBUTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDistributor(RestrictionsString distributor) {
    this.distributor = distributor;
  }


  public SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction elid(RestrictionsString elid) {
    
    this.elid = elid;
    return this;
  }

   /**
   * Get elid
   * @return elid
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getElid() {
    return elid;
  }


  @JsonProperty(JSON_PROPERTY_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setElid(RestrictionsString elid) {
    this.elid = elid;
  }


  public SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction cSupportReactionSw(RestrictionsString cSupportReactionSw) {
    
    this.cSupportReactionSw = cSupportReactionSw;
    return this;
  }

   /**
   * Get cSupportReactionSw
   * @return cSupportReactionSw
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_C_SUPPORT_REACTION_SW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getcSupportReactionSw() {
    return cSupportReactionSw;
  }


  @JsonProperty(JSON_PROPERTY_C_SUPPORT_REACTION_SW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setcSupportReactionSw(RestrictionsString cSupportReactionSw) {
    this.cSupportReactionSw = cSupportReactionSw;
  }


  public SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction beginDate(RestrictionsDate beginDate) {
    
    this.beginDate = beginDate;
    return this;
  }

   /**
   * Get beginDate
   * @return beginDate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BEGIN_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsDate getBeginDate() {
    return beginDate;
  }


  @JsonProperty(JSON_PROPERTY_BEGIN_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBeginDate(RestrictionsDate beginDate) {
    this.beginDate = beginDate;
  }


  public SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction dismissal(RestrictionsString dismissal) {
    
    this.dismissal = dismissal;
    return this;
  }

   /**
   * Get dismissal
   * @return dismissal
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISMISSAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getDismissal() {
    return dismissal;
  }


  @JsonProperty(JSON_PROPERTY_DISMISSAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDismissal(RestrictionsString dismissal) {
    this.dismissal = dismissal;
  }


  public SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction cDismissalEndDate(RestrictionsDate cDismissalEndDate) {
    
    this.cDismissalEndDate = cDismissalEndDate;
    return this;
  }

   /**
   * Get cDismissalEndDate
   * @return cDismissalEndDate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_C_DISMISSAL_END_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsDate getcDismissalEndDate() {
    return cDismissalEndDate;
  }


  @JsonProperty(JSON_PROPERTY_C_DISMISSAL_END_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setcDismissalEndDate(RestrictionsDate cDismissalEndDate) {
    this.cDismissalEndDate = cDismissalEndDate;
  }


  public SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction cSupportSvcHw(RestrictionsString cSupportSvcHw) {
    
    this.cSupportSvcHw = cSupportSvcHw;
    return this;
  }

   /**
   * Get cSupportSvcHw
   * @return cSupportSvcHw
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_C_SUPPORT_SVC_HW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getcSupportSvcHw() {
    return cSupportSvcHw;
  }


  @JsonProperty(JSON_PROPERTY_C_SUPPORT_SVC_HW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setcSupportSvcHw(RestrictionsString cSupportSvcHw) {
    this.cSupportSvcHw = cSupportSvcHw;
  }


  public SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction cRenewal(RestrictionsString cRenewal) {
    
    this.cRenewal = cRenewal;
    return this;
  }

   /**
   * Get cRenewal
   * @return cRenewal
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_C_RENEWAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getcRenewal() {
    return cRenewal;
  }


  @JsonProperty(JSON_PROPERTY_C_RENEWAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setcRenewal(RestrictionsString cRenewal) {
    this.cRenewal = cRenewal;
  }


  public SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction cSupportTimeHw(RestrictionsString cSupportTimeHw) {
    
    this.cSupportTimeHw = cSupportTimeHw;
    return this;
  }

   /**
   * Get cSupportTimeHw
   * @return cSupportTimeHw
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_C_SUPPORT_TIME_HW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getcSupportTimeHw() {
    return cSupportTimeHw;
  }


  @JsonProperty(JSON_PROPERTY_C_SUPPORT_TIME_HW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setcSupportTimeHw(RestrictionsString cSupportTimeHw) {
    this.cSupportTimeHw = cSupportTimeHw;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction softwareInstanceWindowsserviceMaintenanceContractsEntityRestriction = (SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction) o;
    return Objects.equals(this.maintenanceInterval, softwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.maintenanceInterval) &&
        Objects.equals(this.endDate, softwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.endDate) &&
        Objects.equals(this.lifetime, softwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.lifetime) &&
        Objects.equals(this.description, softwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.description) &&
        Objects.equals(this.cDismissalDate, softwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.cDismissalDate) &&
        Objects.equals(this.cAutomaticRenewal, softwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.cAutomaticRenewal) &&
        Objects.equals(this.cDismissalReceivedDate, softwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.cDismissalReceivedDate) &&
        Objects.equals(this.cReftype1, softwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.cReftype1) &&
        Objects.equals(this.dismissalProtection, softwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.dismissalProtection) &&
        Objects.equals(this.nextMaintenanceDate, softwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.nextMaintenanceDate) &&
        Objects.equals(this.cRefvalue1, softwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.cRefvalue1) &&
        Objects.equals(this.cRefvalue2, softwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.cRefvalue2) &&
        Objects.equals(this.id, softwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.id) &&
        Objects.equals(this.cReftype2, softwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.cReftype2) &&
        Objects.equals(this.cDismissalProtectionEnd, softwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.cDismissalProtectionEnd) &&
        Objects.equals(this.lastMaintenanceDate, softwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.lastMaintenanceDate) &&
        Objects.equals(this.maintenancePartner, softwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.maintenancePartner) &&
        Objects.equals(this.cAutoRenewalPeriod, softwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.cAutoRenewalPeriod) &&
        Objects.equals(this.cSupportSvcSw, softwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.cSupportSvcSw) &&
        Objects.equals(this.cRenewalDate, softwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.cRenewalDate) &&
        Objects.equals(this.runtime, softwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.runtime) &&
        Objects.equals(this.cSupportTimeSw, softwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.cSupportTimeSw) &&
        Objects.equals(this.cSupportReactionHw, softwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.cSupportReactionHw) &&
        Objects.equals(this.distributor, softwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.distributor) &&
        Objects.equals(this.elid, softwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.elid) &&
        Objects.equals(this.cSupportReactionSw, softwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.cSupportReactionSw) &&
        Objects.equals(this.beginDate, softwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.beginDate) &&
        Objects.equals(this.dismissal, softwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.dismissal) &&
        Objects.equals(this.cDismissalEndDate, softwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.cDismissalEndDate) &&
        Objects.equals(this.cSupportSvcHw, softwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.cSupportSvcHw) &&
        Objects.equals(this.cRenewal, softwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.cRenewal) &&
        Objects.equals(this.cSupportTimeHw, softwareInstanceWindowsserviceMaintenanceContractsEntityRestriction.cSupportTimeHw);
  }

  @Override
  public int hashCode() {
    return Objects.hash(maintenanceInterval, endDate, lifetime, description, cDismissalDate, cAutomaticRenewal, cDismissalReceivedDate, cReftype1, dismissalProtection, nextMaintenanceDate, cRefvalue1, cRefvalue2, id, cReftype2, cDismissalProtectionEnd, lastMaintenanceDate, maintenancePartner, cAutoRenewalPeriod, cSupportSvcSw, cRenewalDate, runtime, cSupportTimeSw, cSupportReactionHw, distributor, elid, cSupportReactionSw, beginDate, dismissal, cDismissalEndDate, cSupportSvcHw, cRenewal, cSupportTimeHw);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SoftwareInstanceWindowsserviceMaintenanceContractsEntityRestriction {\n");
    sb.append("    maintenanceInterval: ").append(toIndentedString(maintenanceInterval)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    lifetime: ").append(toIndentedString(lifetime)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    cDismissalDate: ").append(toIndentedString(cDismissalDate)).append("\n");
    sb.append("    cAutomaticRenewal: ").append(toIndentedString(cAutomaticRenewal)).append("\n");
    sb.append("    cDismissalReceivedDate: ").append(toIndentedString(cDismissalReceivedDate)).append("\n");
    sb.append("    cReftype1: ").append(toIndentedString(cReftype1)).append("\n");
    sb.append("    dismissalProtection: ").append(toIndentedString(dismissalProtection)).append("\n");
    sb.append("    nextMaintenanceDate: ").append(toIndentedString(nextMaintenanceDate)).append("\n");
    sb.append("    cRefvalue1: ").append(toIndentedString(cRefvalue1)).append("\n");
    sb.append("    cRefvalue2: ").append(toIndentedString(cRefvalue2)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    cReftype2: ").append(toIndentedString(cReftype2)).append("\n");
    sb.append("    cDismissalProtectionEnd: ").append(toIndentedString(cDismissalProtectionEnd)).append("\n");
    sb.append("    lastMaintenanceDate: ").append(toIndentedString(lastMaintenanceDate)).append("\n");
    sb.append("    maintenancePartner: ").append(toIndentedString(maintenancePartner)).append("\n");
    sb.append("    cAutoRenewalPeriod: ").append(toIndentedString(cAutoRenewalPeriod)).append("\n");
    sb.append("    cSupportSvcSw: ").append(toIndentedString(cSupportSvcSw)).append("\n");
    sb.append("    cRenewalDate: ").append(toIndentedString(cRenewalDate)).append("\n");
    sb.append("    runtime: ").append(toIndentedString(runtime)).append("\n");
    sb.append("    cSupportTimeSw: ").append(toIndentedString(cSupportTimeSw)).append("\n");
    sb.append("    cSupportReactionHw: ").append(toIndentedString(cSupportReactionHw)).append("\n");
    sb.append("    distributor: ").append(toIndentedString(distributor)).append("\n");
    sb.append("    elid: ").append(toIndentedString(elid)).append("\n");
    sb.append("    cSupportReactionSw: ").append(toIndentedString(cSupportReactionSw)).append("\n");
    sb.append("    beginDate: ").append(toIndentedString(beginDate)).append("\n");
    sb.append("    dismissal: ").append(toIndentedString(dismissal)).append("\n");
    sb.append("    cDismissalEndDate: ").append(toIndentedString(cDismissalEndDate)).append("\n");
    sb.append("    cSupportSvcHw: ").append(toIndentedString(cSupportSvcHw)).append("\n");
    sb.append("    cRenewal: ").append(toIndentedString(cRenewal)).append("\n");
    sb.append("    cSupportTimeHw: ").append(toIndentedString(cSupportTimeHw)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

