/*
 * Swagger for Command BGE
 * Swagger API for FNT Command Business Gateway
 *
 * The version of the OpenAPI document: 20240226111547
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fntsoftware.businessgateway.entities;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fntsoftware.businessgateway.entities.ObjectAccessInfo;
import com.fntsoftware.businessgateway.entities.ObjectOwnerInfo;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.joda.time.DateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * TerminalSystemAttributesResponseData
 */
@JsonPropertyOrder({
  TerminalSystemAttributesResponseData.JSON_PROPERTY_OWNER,
  TerminalSystemAttributesResponseData.JSON_PROPERTY_LAST_UPDATED_BY,
  TerminalSystemAttributesResponseData.JSON_PROPERTY_LAST_UPDATED_AT,
  TerminalSystemAttributesResponseData.JSON_PROPERTY_OBJECT_OWNER,
  TerminalSystemAttributesResponseData.JSON_PROPERTY_SYSTEM_OWNER,
  TerminalSystemAttributesResponseData.JSON_PROPERTY_ELID,
  TerminalSystemAttributesResponseData.JSON_PROPERTY_UUID,
  TerminalSystemAttributesResponseData.JSON_PROPERTY_CREATE_DATE,
  TerminalSystemAttributesResponseData.JSON_PROPERTY_EXTENDED_OBJECT_ACCESS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-26T11:20:24.990023935Z[Etc/UTC]")
public class TerminalSystemAttributesResponseData {
  public static final String JSON_PROPERTY_OWNER = "owner";
  private String owner;

  public static final String JSON_PROPERTY_LAST_UPDATED_BY = "lastUpdatedBy";
  private String lastUpdatedBy;

  public static final String JSON_PROPERTY_LAST_UPDATED_AT = "lastUpdatedAt";
  private DateTime lastUpdatedAt;

  public static final String JSON_PROPERTY_OBJECT_OWNER = "objectOwner";
  private List<ObjectOwnerInfo> objectOwner;

  public static final String JSON_PROPERTY_SYSTEM_OWNER = "systemOwner";
  private String systemOwner;

  public static final String JSON_PROPERTY_ELID = "elid";
  private String elid;

  public static final String JSON_PROPERTY_UUID = "uuid";
  private String uuid;

  public static final String JSON_PROPERTY_CREATE_DATE = "createDate";
  private DateTime createDate;

  public static final String JSON_PROPERTY_EXTENDED_OBJECT_ACCESS = "extendedObjectAccess";
  private List<ObjectAccessInfo> extendedObjectAccess;

  public TerminalSystemAttributesResponseData() {
  }

  public TerminalSystemAttributesResponseData owner(String owner) {
    
    this.owner = owner;
    return this;
  }

   /**
   * Get owner
   * @return owner
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OWNER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOwner() {
    return owner;
  }


  @JsonProperty(JSON_PROPERTY_OWNER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOwner(String owner) {
    this.owner = owner;
  }


  public TerminalSystemAttributesResponseData lastUpdatedBy(String lastUpdatedBy) {
    
    this.lastUpdatedBy = lastUpdatedBy;
    return this;
  }

   /**
   * Get lastUpdatedBy
   * @return lastUpdatedBy
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_UPDATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLastUpdatedBy() {
    return lastUpdatedBy;
  }


  @JsonProperty(JSON_PROPERTY_LAST_UPDATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastUpdatedBy(String lastUpdatedBy) {
    this.lastUpdatedBy = lastUpdatedBy;
  }


  public TerminalSystemAttributesResponseData lastUpdatedAt(DateTime lastUpdatedAt) {
    
    this.lastUpdatedAt = lastUpdatedAt;
    return this;
  }

   /**
   * Get lastUpdatedAt
   * @return lastUpdatedAt
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DateTime getLastUpdatedAt() {
    return lastUpdatedAt;
  }


  @JsonProperty(JSON_PROPERTY_LAST_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastUpdatedAt(DateTime lastUpdatedAt) {
    this.lastUpdatedAt = lastUpdatedAt;
  }


  public TerminalSystemAttributesResponseData objectOwner(List<ObjectOwnerInfo> objectOwner) {
    
    this.objectOwner = objectOwner;
    return this;
  }

  public TerminalSystemAttributesResponseData addObjectOwnerItem(ObjectOwnerInfo objectOwnerItem) {
    if (this.objectOwner == null) {
      this.objectOwner = new ArrayList<>();
    }
    this.objectOwner.add(objectOwnerItem);
    return this;
  }

   /**
   * Get objectOwner
   * @return objectOwner
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OBJECT_OWNER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ObjectOwnerInfo> getObjectOwner() {
    return objectOwner;
  }


  @JsonProperty(JSON_PROPERTY_OBJECT_OWNER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setObjectOwner(List<ObjectOwnerInfo> objectOwner) {
    this.objectOwner = objectOwner;
  }


  public TerminalSystemAttributesResponseData systemOwner(String systemOwner) {
    
    this.systemOwner = systemOwner;
    return this;
  }

   /**
   * Get systemOwner
   * @return systemOwner
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SYSTEM_OWNER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSystemOwner() {
    return systemOwner;
  }


  @JsonProperty(JSON_PROPERTY_SYSTEM_OWNER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSystemOwner(String systemOwner) {
    this.systemOwner = systemOwner;
  }


  public TerminalSystemAttributesResponseData elid(String elid) {
    
    this.elid = elid;
    return this;
  }

   /**
   * Get elid
   * @return elid
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getElid() {
    return elid;
  }


  @JsonProperty(JSON_PROPERTY_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setElid(String elid) {
    this.elid = elid;
  }


  public TerminalSystemAttributesResponseData uuid(String uuid) {
    
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUuid() {
    return uuid;
  }


  @JsonProperty(JSON_PROPERTY_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  public TerminalSystemAttributesResponseData createDate(DateTime createDate) {
    
    this.createDate = createDate;
    return this;
  }

   /**
   * Get createDate
   * @return createDate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DateTime getCreateDate() {
    return createDate;
  }


  @JsonProperty(JSON_PROPERTY_CREATE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreateDate(DateTime createDate) {
    this.createDate = createDate;
  }


  public TerminalSystemAttributesResponseData extendedObjectAccess(List<ObjectAccessInfo> extendedObjectAccess) {
    
    this.extendedObjectAccess = extendedObjectAccess;
    return this;
  }

  public TerminalSystemAttributesResponseData addExtendedObjectAccessItem(ObjectAccessInfo extendedObjectAccessItem) {
    if (this.extendedObjectAccess == null) {
      this.extendedObjectAccess = new ArrayList<>();
    }
    this.extendedObjectAccess.add(extendedObjectAccessItem);
    return this;
  }

   /**
   * Get extendedObjectAccess
   * @return extendedObjectAccess
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTENDED_OBJECT_ACCESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ObjectAccessInfo> getExtendedObjectAccess() {
    return extendedObjectAccess;
  }


  @JsonProperty(JSON_PROPERTY_EXTENDED_OBJECT_ACCESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtendedObjectAccess(List<ObjectAccessInfo> extendedObjectAccess) {
    this.extendedObjectAccess = extendedObjectAccess;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TerminalSystemAttributesResponseData terminalSystemAttributesResponseData = (TerminalSystemAttributesResponseData) o;
    return Objects.equals(this.owner, terminalSystemAttributesResponseData.owner) &&
        Objects.equals(this.lastUpdatedBy, terminalSystemAttributesResponseData.lastUpdatedBy) &&
        Objects.equals(this.lastUpdatedAt, terminalSystemAttributesResponseData.lastUpdatedAt) &&
        Objects.equals(this.objectOwner, terminalSystemAttributesResponseData.objectOwner) &&
        Objects.equals(this.systemOwner, terminalSystemAttributesResponseData.systemOwner) &&
        Objects.equals(this.elid, terminalSystemAttributesResponseData.elid) &&
        Objects.equals(this.uuid, terminalSystemAttributesResponseData.uuid) &&
        Objects.equals(this.createDate, terminalSystemAttributesResponseData.createDate) &&
        Objects.equals(this.extendedObjectAccess, terminalSystemAttributesResponseData.extendedObjectAccess);
  }

  @Override
  public int hashCode() {
    return Objects.hash(owner, lastUpdatedBy, lastUpdatedAt, objectOwner, systemOwner, elid, uuid, createDate, extendedObjectAccess);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TerminalSystemAttributesResponseData {\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    lastUpdatedBy: ").append(toIndentedString(lastUpdatedBy)).append("\n");
    sb.append("    lastUpdatedAt: ").append(toIndentedString(lastUpdatedAt)).append("\n");
    sb.append("    objectOwner: ").append(toIndentedString(objectOwner)).append("\n");
    sb.append("    systemOwner: ").append(toIndentedString(systemOwner)).append("\n");
    sb.append("    elid: ").append(toIndentedString(elid)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    createDate: ").append(toIndentedString(createDate)).append("\n");
    sb.append("    extendedObjectAccess: ").append(toIndentedString(extendedObjectAccess)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

