/*
 * Swagger for Command BGE
 * Swagger API for FNT Command Business Gateway
 *
 * The version of the OpenAPI document: 20240131110751
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fntsoftware.businessgateway.entities;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * UpdateCableMasterDataCableUpdateConductorRequestData
 */
@JsonPropertyOrder({
  UpdateCableMasterDataCableUpdateConductorRequestData.JSON_PROPERTY_CONDUCTOR_ID,
  UpdateCableMasterDataCableUpdateConductorRequestData.JSON_PROPERTY_LENGTH,
  UpdateCableMasterDataCableUpdateConductorRequestData.JSON_PROPERTY_REMARK,
  UpdateCableMasterDataCableUpdateConductorRequestData.JSON_PROPERTY_MEDIUM,
  UpdateCableMasterDataCableUpdateConductorRequestData.JSON_PROPERTY_CATEGORY,
  UpdateCableMasterDataCableUpdateConductorRequestData.JSON_PROPERTY_CONDUCTOR_COLOR,
  UpdateCableMasterDataCableUpdateConductorRequestData.JSON_PROPERTY_TYPE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-31T11:10:37.320689708Z[Etc/UTC]")
public class UpdateCableMasterDataCableUpdateConductorRequestData {
  public static final String JSON_PROPERTY_CONDUCTOR_ID = "conductorId";
  private String conductorId;

  public static final String JSON_PROPERTY_LENGTH = "length";
  private BigDecimal length;

  public static final String JSON_PROPERTY_REMARK = "remark";
  private String remark;

  public static final String JSON_PROPERTY_MEDIUM = "medium";
  private String medium;

  public static final String JSON_PROPERTY_CATEGORY = "category";
  private String category;

  public static final String JSON_PROPERTY_CONDUCTOR_COLOR = "conductorColor";
  private String conductorColor;

  public static final String JSON_PROPERTY_TYPE = "type";
  private String type;

  public UpdateCableMasterDataCableUpdateConductorRequestData() {
  }

  public UpdateCableMasterDataCableUpdateConductorRequestData conductorId(String conductorId) {
    
    this.conductorId = conductorId;
    return this;
  }

   /**
   * Get conductorId
   * @return conductorId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONDUCTOR_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getConductorId() {
    return conductorId;
  }


  @JsonProperty(JSON_PROPERTY_CONDUCTOR_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConductorId(String conductorId) {
    this.conductorId = conductorId;
  }


  public UpdateCableMasterDataCableUpdateConductorRequestData length(BigDecimal length) {
    
    this.length = length;
    return this;
  }

   /**
   * Get length
   * @return length
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getLength() {
    return length;
  }


  @JsonProperty(JSON_PROPERTY_LENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLength(BigDecimal length) {
    this.length = length;
  }


  public UpdateCableMasterDataCableUpdateConductorRequestData remark(String remark) {
    
    this.remark = remark;
    return this;
  }

   /**
   * Get remark
   * @return remark
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REMARK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRemark() {
    return remark;
  }


  @JsonProperty(JSON_PROPERTY_REMARK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRemark(String remark) {
    this.remark = remark;
  }


  public UpdateCableMasterDataCableUpdateConductorRequestData medium(String medium) {
    
    this.medium = medium;
    return this;
  }

   /**
   * Get medium
   * @return medium
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MEDIUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMedium() {
    return medium;
  }


  @JsonProperty(JSON_PROPERTY_MEDIUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMedium(String medium) {
    this.medium = medium;
  }


  public UpdateCableMasterDataCableUpdateConductorRequestData category(String category) {
    
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCategory() {
    return category;
  }


  @JsonProperty(JSON_PROPERTY_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCategory(String category) {
    this.category = category;
  }


  public UpdateCableMasterDataCableUpdateConductorRequestData conductorColor(String conductorColor) {
    
    this.conductorColor = conductorColor;
    return this;
  }

   /**
   * Get conductorColor
   * @return conductorColor
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONDUCTOR_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getConductorColor() {
    return conductorColor;
  }


  @JsonProperty(JSON_PROPERTY_CONDUCTOR_COLOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConductorColor(String conductorColor) {
    this.conductorColor = conductorColor;
  }


  public UpdateCableMasterDataCableUpdateConductorRequestData type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateCableMasterDataCableUpdateConductorRequestData updateCableMasterDataCableUpdateConductorRequestData = (UpdateCableMasterDataCableUpdateConductorRequestData) o;
    return Objects.equals(this.conductorId, updateCableMasterDataCableUpdateConductorRequestData.conductorId) &&
        Objects.equals(this.length, updateCableMasterDataCableUpdateConductorRequestData.length) &&
        Objects.equals(this.remark, updateCableMasterDataCableUpdateConductorRequestData.remark) &&
        Objects.equals(this.medium, updateCableMasterDataCableUpdateConductorRequestData.medium) &&
        Objects.equals(this.category, updateCableMasterDataCableUpdateConductorRequestData.category) &&
        Objects.equals(this.conductorColor, updateCableMasterDataCableUpdateConductorRequestData.conductorColor) &&
        Objects.equals(this.type, updateCableMasterDataCableUpdateConductorRequestData.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conductorId, length, remark, medium, category, conductorColor, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateCableMasterDataCableUpdateConductorRequestData {\n");
    sb.append("    conductorId: ").append(toIndentedString(conductorId)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("    remark: ").append(toIndentedString(remark)).append("\n");
    sb.append("    medium: ").append(toIndentedString(medium)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    conductorColor: ").append(toIndentedString(conductorColor)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

