/*
 * Swagger for Command BGE
 * Swagger API for FNT Command Business Gateway
 *
 * The version of the OpenAPI document: 20240226111547
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fntsoftware.businessgateway.entities;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * UpdateVirtualServerUpdateVirtualDriveRequestData
 */
@JsonPropertyOrder({
  UpdateVirtualServerUpdateVirtualDriveRequestData.JSON_PROPERTY_PASS_THROUGH,
  UpdateVirtualServerUpdateVirtualDriveRequestData.JSON_PROPERTY_DRIVE_MODE,
  UpdateVirtualServerUpdateVirtualDriveRequestData.JSON_PROPERTY_VIRTUAL_DEVICE_MODE,
  UpdateVirtualServerUpdateVirtualDriveRequestData.JSON_PROPERTY_LOCATION,
  UpdateVirtualServerUpdateVirtualDriveRequestData.JSON_PROPERTY_LINK_ELID,
  UpdateVirtualServerUpdateVirtualDriveRequestData.JSON_PROPERTY_DRIVE_PATH
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-26T11:20:24.990023935Z[Etc/UTC]")
public class UpdateVirtualServerUpdateVirtualDriveRequestData {
  public static final String JSON_PROPERTY_PASS_THROUGH = "passThrough";
  private Boolean passThrough;

  public static final String JSON_PROPERTY_DRIVE_MODE = "driveMode";
  private String driveMode;

  public static final String JSON_PROPERTY_VIRTUAL_DEVICE_MODE = "virtualDeviceMode";
  private String virtualDeviceMode;

  public static final String JSON_PROPERTY_LOCATION = "location";
  private String location;

  public static final String JSON_PROPERTY_LINK_ELID = "linkElid";
  private String linkElid;

  public static final String JSON_PROPERTY_DRIVE_PATH = "drivePath";
  private String drivePath;

  public UpdateVirtualServerUpdateVirtualDriveRequestData() {
  }

  public UpdateVirtualServerUpdateVirtualDriveRequestData passThrough(Boolean passThrough) {
    
    this.passThrough = passThrough;
    return this;
  }

   /**
   * Get passThrough
   * @return passThrough
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PASS_THROUGH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPassThrough() {
    return passThrough;
  }


  @JsonProperty(JSON_PROPERTY_PASS_THROUGH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPassThrough(Boolean passThrough) {
    this.passThrough = passThrough;
  }


  public UpdateVirtualServerUpdateVirtualDriveRequestData driveMode(String driveMode) {
    
    this.driveMode = driveMode;
    return this;
  }

   /**
   * Get driveMode
   * @return driveMode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DRIVE_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDriveMode() {
    return driveMode;
  }


  @JsonProperty(JSON_PROPERTY_DRIVE_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDriveMode(String driveMode) {
    this.driveMode = driveMode;
  }


  public UpdateVirtualServerUpdateVirtualDriveRequestData virtualDeviceMode(String virtualDeviceMode) {
    
    this.virtualDeviceMode = virtualDeviceMode;
    return this;
  }

   /**
   * Get virtualDeviceMode
   * @return virtualDeviceMode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VIRTUAL_DEVICE_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVirtualDeviceMode() {
    return virtualDeviceMode;
  }


  @JsonProperty(JSON_PROPERTY_VIRTUAL_DEVICE_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVirtualDeviceMode(String virtualDeviceMode) {
    this.virtualDeviceMode = virtualDeviceMode;
  }


  public UpdateVirtualServerUpdateVirtualDriveRequestData location(String location) {
    
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLocation() {
    return location;
  }


  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocation(String location) {
    this.location = location;
  }


  public UpdateVirtualServerUpdateVirtualDriveRequestData linkElid(String linkElid) {
    
    this.linkElid = linkElid;
    return this;
  }

   /**
   * Get linkElid
   * @return linkElid
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINK_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLinkElid() {
    return linkElid;
  }


  @JsonProperty(JSON_PROPERTY_LINK_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLinkElid(String linkElid) {
    this.linkElid = linkElid;
  }


  public UpdateVirtualServerUpdateVirtualDriveRequestData drivePath(String drivePath) {
    
    this.drivePath = drivePath;
    return this;
  }

   /**
   * Get drivePath
   * @return drivePath
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DRIVE_PATH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDrivePath() {
    return drivePath;
  }


  @JsonProperty(JSON_PROPERTY_DRIVE_PATH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDrivePath(String drivePath) {
    this.drivePath = drivePath;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateVirtualServerUpdateVirtualDriveRequestData updateVirtualServerUpdateVirtualDriveRequestData = (UpdateVirtualServerUpdateVirtualDriveRequestData) o;
    return Objects.equals(this.passThrough, updateVirtualServerUpdateVirtualDriveRequestData.passThrough) &&
        Objects.equals(this.driveMode, updateVirtualServerUpdateVirtualDriveRequestData.driveMode) &&
        Objects.equals(this.virtualDeviceMode, updateVirtualServerUpdateVirtualDriveRequestData.virtualDeviceMode) &&
        Objects.equals(this.location, updateVirtualServerUpdateVirtualDriveRequestData.location) &&
        Objects.equals(this.linkElid, updateVirtualServerUpdateVirtualDriveRequestData.linkElid) &&
        Objects.equals(this.drivePath, updateVirtualServerUpdateVirtualDriveRequestData.drivePath);
  }

  @Override
  public int hashCode() {
    return Objects.hash(passThrough, driveMode, virtualDeviceMode, location, linkElid, drivePath);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateVirtualServerUpdateVirtualDriveRequestData {\n");
    sb.append("    passThrough: ").append(toIndentedString(passThrough)).append("\n");
    sb.append("    driveMode: ").append(toIndentedString(driveMode)).append("\n");
    sb.append("    virtualDeviceMode: ").append(toIndentedString(virtualDeviceMode)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    linkElid: ").append(toIndentedString(linkElid)).append("\n");
    sb.append("    drivePath: ").append(toIndentedString(drivePath)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

