/*
 * Swagger for Command BGE
 * Swagger API for FNT Command Business Gateway
 *
 * The version of the OpenAPI document: 20240304133000
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fntsoftware.businessgateway.entities;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * UpdateIpv6NetworkUpdateLinkCustomIpaccessSvcRequestData
 */
@JsonPropertyOrder({
  UpdateIpv6NetworkUpdateLinkCustomIpaccessSvcRequestData.JSON_PROPERTY_FUNCTION,
  UpdateIpv6NetworkUpdateLinkCustomIpaccessSvcRequestData.JSON_PROPERTY_LINK_ELID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-04T13:31:32.601557352Z[Etc/UTC]")
public class UpdateIpv6NetworkUpdateLinkCustomIpaccessSvcRequestData {
  public static final String JSON_PROPERTY_FUNCTION = "function";
  private String function;

  public static final String JSON_PROPERTY_LINK_ELID = "linkElid";
  private String linkElid;

  public UpdateIpv6NetworkUpdateLinkCustomIpaccessSvcRequestData() {
  }

  public UpdateIpv6NetworkUpdateLinkCustomIpaccessSvcRequestData function(String function) {
    
    this.function = function;
    return this;
  }

   /**
   * Get function
   * @return function
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FUNCTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFunction() {
    return function;
  }


  @JsonProperty(JSON_PROPERTY_FUNCTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFunction(String function) {
    this.function = function;
  }


  public UpdateIpv6NetworkUpdateLinkCustomIpaccessSvcRequestData linkElid(String linkElid) {
    
    this.linkElid = linkElid;
    return this;
  }

   /**
   * Get linkElid
   * @return linkElid
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINK_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLinkElid() {
    return linkElid;
  }


  @JsonProperty(JSON_PROPERTY_LINK_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLinkElid(String linkElid) {
    this.linkElid = linkElid;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateIpv6NetworkUpdateLinkCustomIpaccessSvcRequestData updateIpv6NetworkUpdateLinkCustomIpaccessSvcRequestData = (UpdateIpv6NetworkUpdateLinkCustomIpaccessSvcRequestData) o;
    return Objects.equals(this.function, updateIpv6NetworkUpdateLinkCustomIpaccessSvcRequestData.function) &&
        Objects.equals(this.linkElid, updateIpv6NetworkUpdateLinkCustomIpaccessSvcRequestData.linkElid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(function, linkElid);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateIpv6NetworkUpdateLinkCustomIpaccessSvcRequestData {\n");
    sb.append("    function: ").append(toIndentedString(function)).append("\n");
    sb.append("    linkElid: ").append(toIndentedString(linkElid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

