/*
 * Swagger for Command BGE
 * Swagger API for FNT Command Business Gateway
 *
 * The version of the OpenAPI document: 20240131110751
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fntsoftware.businessgateway.entities;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fntsoftware.businessgateway.entities.UpdateJunctionBoxFistCreateLinkContractRequestData;
import com.fntsoftware.businessgateway.entities.UpdateJunctionBoxFistCreateLinkFrameContractRequestData;
import com.fntsoftware.businessgateway.entities.UpdateJunctionBoxFistCreateLinkMaintenanceContractRequestData;
import com.fntsoftware.businessgateway.entities.UpdateJunctionBoxFistCreateLinkOrganizationRequestData;
import com.fntsoftware.businessgateway.entities.UpdateJunctionBoxFistCreateLinkPersonGroupRequestData;
import com.fntsoftware.businessgateway.entities.UpdateJunctionBoxFistCreateLinkPersonRequestData;
import com.fntsoftware.businessgateway.entities.UpdateJunctionBoxFistCreateLinkSiteRequestData;
import com.fntsoftware.businessgateway.entities.UpdateJunctionBoxFistDeleteLinkContractRequestData;
import com.fntsoftware.businessgateway.entities.UpdateJunctionBoxFistDeleteLinkFrameContractRequestData;
import com.fntsoftware.businessgateway.entities.UpdateJunctionBoxFistDeleteLinkMaintenanceContractRequestData;
import com.fntsoftware.businessgateway.entities.UpdateJunctionBoxFistDeleteLinkOrganizationRequestData;
import com.fntsoftware.businessgateway.entities.UpdateJunctionBoxFistDeleteLinkPersonGroupRequestData;
import com.fntsoftware.businessgateway.entities.UpdateJunctionBoxFistDeleteLinkPersonRequestData;
import com.fntsoftware.businessgateway.entities.UpdateJunctionBoxFistDeleteLinkSiteRequestData;
import com.fntsoftware.businessgateway.entities.UpdateJunctionBoxFistInstallOperatingSystemInstallationRequestData;
import com.fntsoftware.businessgateway.entities.UpdateJunctionBoxFistSwapOperatingSystemInstallationRequestData;
import com.fntsoftware.businessgateway.entities.UpdateJunctionBoxFistUpdateLinkOrganizationRequestData;
import com.fntsoftware.businessgateway.entities.UpdateJunctionBoxFistUpdateLinkPersonGroupRequestData;
import com.fntsoftware.businessgateway.entities.UpdateJunctionBoxFistUpdateLinkPersonRequestData;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * UpdateJunctionBoxFistRequestData
 */
@JsonPropertyOrder({
  UpdateJunctionBoxFistRequestData.JSON_PROPERTY_SOURCE_ID,
  UpdateJunctionBoxFistRequestData.JSON_PROPERTY_SOURCE_SYSTEM,
  UpdateJunctionBoxFistRequestData.JSON_PROPERTY_CONTEXT_ID,
  UpdateJunctionBoxFistRequestData.JSON_PROPERTY_REMARK,
  UpdateJunctionBoxFistRequestData.JSON_PROPERTY_VISIBLE_ID,
  UpdateJunctionBoxFistRequestData.JSON_PROPERTY_ID,
  UpdateJunctionBoxFistRequestData.JSON_PROPERTY_SERIAL_NO,
  UpdateJunctionBoxFistRequestData.JSON_PROPERTY_CREATE_LINK_CONTRACT,
  UpdateJunctionBoxFistRequestData.JSON_PROPERTY_CREATE_LINK_FRAME_CONTRACT,
  UpdateJunctionBoxFistRequestData.JSON_PROPERTY_CREATE_LINK_MAINTENANCE_CONTRACT,
  UpdateJunctionBoxFistRequestData.JSON_PROPERTY_CREATE_LINK_ORGANIZATION,
  UpdateJunctionBoxFistRequestData.JSON_PROPERTY_CREATE_LINK_PERSON,
  UpdateJunctionBoxFistRequestData.JSON_PROPERTY_CREATE_LINK_PERSON_GROUP,
  UpdateJunctionBoxFistRequestData.JSON_PROPERTY_CREATE_LINK_SITE,
  UpdateJunctionBoxFistRequestData.JSON_PROPERTY_DELETE_LINK_CONTRACT,
  UpdateJunctionBoxFistRequestData.JSON_PROPERTY_DELETE_LINK_FRAME_CONTRACT,
  UpdateJunctionBoxFistRequestData.JSON_PROPERTY_DELETE_LINK_MAINTENANCE_CONTRACT,
  UpdateJunctionBoxFistRequestData.JSON_PROPERTY_DELETE_LINK_ORGANIZATION,
  UpdateJunctionBoxFistRequestData.JSON_PROPERTY_DELETE_LINK_PERSON,
  UpdateJunctionBoxFistRequestData.JSON_PROPERTY_DELETE_LINK_PERSON_GROUP,
  UpdateJunctionBoxFistRequestData.JSON_PROPERTY_DELETE_LINK_SITE,
  UpdateJunctionBoxFistRequestData.JSON_PROPERTY_INSTALL_OPERATING_SYSTEM_INSTALLATION,
  UpdateJunctionBoxFistRequestData.JSON_PROPERTY_SWAP_OPERATING_SYSTEM_INSTALLATION,
  UpdateJunctionBoxFistRequestData.JSON_PROPERTY_UPDATE_LINK_ORGANIZATION,
  UpdateJunctionBoxFistRequestData.JSON_PROPERTY_UPDATE_LINK_PERSON,
  UpdateJunctionBoxFistRequestData.JSON_PROPERTY_UPDATE_LINK_PERSON_GROUP
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-31T11:10:37.320689708Z[Etc/UTC]")
public class UpdateJunctionBoxFistRequestData {
  public static final String JSON_PROPERTY_SOURCE_ID = "sourceId";
  private String sourceId;

  public static final String JSON_PROPERTY_SOURCE_SYSTEM = "sourceSystem";
  private String sourceSystem;

  public static final String JSON_PROPERTY_CONTEXT_ID = "contextId";
  private String contextId;

  public static final String JSON_PROPERTY_REMARK = "remark";
  private String remark;

  public static final String JSON_PROPERTY_VISIBLE_ID = "visibleId";
  private String visibleId;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_SERIAL_NO = "serialNo";
  private String serialNo;

  public static final String JSON_PROPERTY_CREATE_LINK_CONTRACT = "createLinkContract";
  private List<UpdateJunctionBoxFistCreateLinkContractRequestData> createLinkContract;

  public static final String JSON_PROPERTY_CREATE_LINK_FRAME_CONTRACT = "createLinkFrameContract";
  private List<UpdateJunctionBoxFistCreateLinkFrameContractRequestData> createLinkFrameContract;

  public static final String JSON_PROPERTY_CREATE_LINK_MAINTENANCE_CONTRACT = "createLinkMaintenanceContract";
  private List<UpdateJunctionBoxFistCreateLinkMaintenanceContractRequestData> createLinkMaintenanceContract;

  public static final String JSON_PROPERTY_CREATE_LINK_ORGANIZATION = "createLinkOrganization";
  private List<UpdateJunctionBoxFistCreateLinkOrganizationRequestData> createLinkOrganization;

  public static final String JSON_PROPERTY_CREATE_LINK_PERSON = "createLinkPerson";
  private List<UpdateJunctionBoxFistCreateLinkPersonRequestData> createLinkPerson;

  public static final String JSON_PROPERTY_CREATE_LINK_PERSON_GROUP = "createLinkPersonGroup";
  private List<UpdateJunctionBoxFistCreateLinkPersonGroupRequestData> createLinkPersonGroup;

  public static final String JSON_PROPERTY_CREATE_LINK_SITE = "createLinkSite";
  private List<UpdateJunctionBoxFistCreateLinkSiteRequestData> createLinkSite;

  public static final String JSON_PROPERTY_DELETE_LINK_CONTRACT = "deleteLinkContract";
  private List<UpdateJunctionBoxFistDeleteLinkContractRequestData> deleteLinkContract;

  public static final String JSON_PROPERTY_DELETE_LINK_FRAME_CONTRACT = "deleteLinkFrameContract";
  private List<UpdateJunctionBoxFistDeleteLinkFrameContractRequestData> deleteLinkFrameContract;

  public static final String JSON_PROPERTY_DELETE_LINK_MAINTENANCE_CONTRACT = "deleteLinkMaintenanceContract";
  private List<UpdateJunctionBoxFistDeleteLinkMaintenanceContractRequestData> deleteLinkMaintenanceContract;

  public static final String JSON_PROPERTY_DELETE_LINK_ORGANIZATION = "deleteLinkOrganization";
  private List<UpdateJunctionBoxFistDeleteLinkOrganizationRequestData> deleteLinkOrganization;

  public static final String JSON_PROPERTY_DELETE_LINK_PERSON = "deleteLinkPerson";
  private List<UpdateJunctionBoxFistDeleteLinkPersonRequestData> deleteLinkPerson;

  public static final String JSON_PROPERTY_DELETE_LINK_PERSON_GROUP = "deleteLinkPersonGroup";
  private List<UpdateJunctionBoxFistDeleteLinkPersonGroupRequestData> deleteLinkPersonGroup;

  public static final String JSON_PROPERTY_DELETE_LINK_SITE = "deleteLinkSite";
  private List<UpdateJunctionBoxFistDeleteLinkSiteRequestData> deleteLinkSite;

  public static final String JSON_PROPERTY_INSTALL_OPERATING_SYSTEM_INSTALLATION = "installOperatingSystemInstallation";
  private UpdateJunctionBoxFistInstallOperatingSystemInstallationRequestData installOperatingSystemInstallation;

  public static final String JSON_PROPERTY_SWAP_OPERATING_SYSTEM_INSTALLATION = "swapOperatingSystemInstallation";
  private UpdateJunctionBoxFistSwapOperatingSystemInstallationRequestData swapOperatingSystemInstallation;

  public static final String JSON_PROPERTY_UPDATE_LINK_ORGANIZATION = "updateLinkOrganization";
  private List<UpdateJunctionBoxFistUpdateLinkOrganizationRequestData> updateLinkOrganization;

  public static final String JSON_PROPERTY_UPDATE_LINK_PERSON = "updateLinkPerson";
  private List<UpdateJunctionBoxFistUpdateLinkPersonRequestData> updateLinkPerson;

  public static final String JSON_PROPERTY_UPDATE_LINK_PERSON_GROUP = "updateLinkPersonGroup";
  private List<UpdateJunctionBoxFistUpdateLinkPersonGroupRequestData> updateLinkPersonGroup;

  public UpdateJunctionBoxFistRequestData() {
  }

  public UpdateJunctionBoxFistRequestData sourceId(String sourceId) {
    
    this.sourceId = sourceId;
    return this;
  }

   /**
   * Get sourceId
   * @return sourceId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SOURCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSourceId() {
    return sourceId;
  }


  @JsonProperty(JSON_PROPERTY_SOURCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSourceId(String sourceId) {
    this.sourceId = sourceId;
  }


  public UpdateJunctionBoxFistRequestData sourceSystem(String sourceSystem) {
    
    this.sourceSystem = sourceSystem;
    return this;
  }

   /**
   * Get sourceSystem
   * @return sourceSystem
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SOURCE_SYSTEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSourceSystem() {
    return sourceSystem;
  }


  @JsonProperty(JSON_PROPERTY_SOURCE_SYSTEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSourceSystem(String sourceSystem) {
    this.sourceSystem = sourceSystem;
  }


  public UpdateJunctionBoxFistRequestData contextId(String contextId) {
    
    this.contextId = contextId;
    return this;
  }

   /**
   * Get contextId
   * @return contextId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTEXT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getContextId() {
    return contextId;
  }


  @JsonProperty(JSON_PROPERTY_CONTEXT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContextId(String contextId) {
    this.contextId = contextId;
  }


  public UpdateJunctionBoxFistRequestData remark(String remark) {
    
    this.remark = remark;
    return this;
  }

   /**
   * Get remark
   * @return remark
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REMARK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRemark() {
    return remark;
  }


  @JsonProperty(JSON_PROPERTY_REMARK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRemark(String remark) {
    this.remark = remark;
  }


  public UpdateJunctionBoxFistRequestData visibleId(String visibleId) {
    
    this.visibleId = visibleId;
    return this;
  }

   /**
   * Get visibleId
   * @return visibleId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VISIBLE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVisibleId() {
    return visibleId;
  }


  @JsonProperty(JSON_PROPERTY_VISIBLE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVisibleId(String visibleId) {
    this.visibleId = visibleId;
  }


  public UpdateJunctionBoxFistRequestData id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public UpdateJunctionBoxFistRequestData serialNo(String serialNo) {
    
    this.serialNo = serialNo;
    return this;
  }

   /**
   * Get serialNo
   * @return serialNo
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SERIAL_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSerialNo() {
    return serialNo;
  }


  @JsonProperty(JSON_PROPERTY_SERIAL_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSerialNo(String serialNo) {
    this.serialNo = serialNo;
  }


  public UpdateJunctionBoxFistRequestData createLinkContract(List<UpdateJunctionBoxFistCreateLinkContractRequestData> createLinkContract) {
    
    this.createLinkContract = createLinkContract;
    return this;
  }

  public UpdateJunctionBoxFistRequestData addCreateLinkContractItem(UpdateJunctionBoxFistCreateLinkContractRequestData createLinkContractItem) {
    if (this.createLinkContract == null) {
      this.createLinkContract = new ArrayList<>();
    }
    this.createLinkContract.add(createLinkContractItem);
    return this;
  }

   /**
   * Get createLinkContract
   * @return createLinkContract
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATE_LINK_CONTRACT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<UpdateJunctionBoxFistCreateLinkContractRequestData> getCreateLinkContract() {
    return createLinkContract;
  }


  @JsonProperty(JSON_PROPERTY_CREATE_LINK_CONTRACT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreateLinkContract(List<UpdateJunctionBoxFistCreateLinkContractRequestData> createLinkContract) {
    this.createLinkContract = createLinkContract;
  }


  public UpdateJunctionBoxFistRequestData createLinkFrameContract(List<UpdateJunctionBoxFistCreateLinkFrameContractRequestData> createLinkFrameContract) {
    
    this.createLinkFrameContract = createLinkFrameContract;
    return this;
  }

  public UpdateJunctionBoxFistRequestData addCreateLinkFrameContractItem(UpdateJunctionBoxFistCreateLinkFrameContractRequestData createLinkFrameContractItem) {
    if (this.createLinkFrameContract == null) {
      this.createLinkFrameContract = new ArrayList<>();
    }
    this.createLinkFrameContract.add(createLinkFrameContractItem);
    return this;
  }

   /**
   * Get createLinkFrameContract
   * @return createLinkFrameContract
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATE_LINK_FRAME_CONTRACT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<UpdateJunctionBoxFistCreateLinkFrameContractRequestData> getCreateLinkFrameContract() {
    return createLinkFrameContract;
  }


  @JsonProperty(JSON_PROPERTY_CREATE_LINK_FRAME_CONTRACT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreateLinkFrameContract(List<UpdateJunctionBoxFistCreateLinkFrameContractRequestData> createLinkFrameContract) {
    this.createLinkFrameContract = createLinkFrameContract;
  }


  public UpdateJunctionBoxFistRequestData createLinkMaintenanceContract(List<UpdateJunctionBoxFistCreateLinkMaintenanceContractRequestData> createLinkMaintenanceContract) {
    
    this.createLinkMaintenanceContract = createLinkMaintenanceContract;
    return this;
  }

  public UpdateJunctionBoxFistRequestData addCreateLinkMaintenanceContractItem(UpdateJunctionBoxFistCreateLinkMaintenanceContractRequestData createLinkMaintenanceContractItem) {
    if (this.createLinkMaintenanceContract == null) {
      this.createLinkMaintenanceContract = new ArrayList<>();
    }
    this.createLinkMaintenanceContract.add(createLinkMaintenanceContractItem);
    return this;
  }

   /**
   * Get createLinkMaintenanceContract
   * @return createLinkMaintenanceContract
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATE_LINK_MAINTENANCE_CONTRACT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<UpdateJunctionBoxFistCreateLinkMaintenanceContractRequestData> getCreateLinkMaintenanceContract() {
    return createLinkMaintenanceContract;
  }


  @JsonProperty(JSON_PROPERTY_CREATE_LINK_MAINTENANCE_CONTRACT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreateLinkMaintenanceContract(List<UpdateJunctionBoxFistCreateLinkMaintenanceContractRequestData> createLinkMaintenanceContract) {
    this.createLinkMaintenanceContract = createLinkMaintenanceContract;
  }


  public UpdateJunctionBoxFistRequestData createLinkOrganization(List<UpdateJunctionBoxFistCreateLinkOrganizationRequestData> createLinkOrganization) {
    
    this.createLinkOrganization = createLinkOrganization;
    return this;
  }

  public UpdateJunctionBoxFistRequestData addCreateLinkOrganizationItem(UpdateJunctionBoxFistCreateLinkOrganizationRequestData createLinkOrganizationItem) {
    if (this.createLinkOrganization == null) {
      this.createLinkOrganization = new ArrayList<>();
    }
    this.createLinkOrganization.add(createLinkOrganizationItem);
    return this;
  }

   /**
   * Get createLinkOrganization
   * @return createLinkOrganization
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATE_LINK_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<UpdateJunctionBoxFistCreateLinkOrganizationRequestData> getCreateLinkOrganization() {
    return createLinkOrganization;
  }


  @JsonProperty(JSON_PROPERTY_CREATE_LINK_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreateLinkOrganization(List<UpdateJunctionBoxFistCreateLinkOrganizationRequestData> createLinkOrganization) {
    this.createLinkOrganization = createLinkOrganization;
  }


  public UpdateJunctionBoxFistRequestData createLinkPerson(List<UpdateJunctionBoxFistCreateLinkPersonRequestData> createLinkPerson) {
    
    this.createLinkPerson = createLinkPerson;
    return this;
  }

  public UpdateJunctionBoxFistRequestData addCreateLinkPersonItem(UpdateJunctionBoxFistCreateLinkPersonRequestData createLinkPersonItem) {
    if (this.createLinkPerson == null) {
      this.createLinkPerson = new ArrayList<>();
    }
    this.createLinkPerson.add(createLinkPersonItem);
    return this;
  }

   /**
   * Get createLinkPerson
   * @return createLinkPerson
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATE_LINK_PERSON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<UpdateJunctionBoxFistCreateLinkPersonRequestData> getCreateLinkPerson() {
    return createLinkPerson;
  }


  @JsonProperty(JSON_PROPERTY_CREATE_LINK_PERSON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreateLinkPerson(List<UpdateJunctionBoxFistCreateLinkPersonRequestData> createLinkPerson) {
    this.createLinkPerson = createLinkPerson;
  }


  public UpdateJunctionBoxFistRequestData createLinkPersonGroup(List<UpdateJunctionBoxFistCreateLinkPersonGroupRequestData> createLinkPersonGroup) {
    
    this.createLinkPersonGroup = createLinkPersonGroup;
    return this;
  }

  public UpdateJunctionBoxFistRequestData addCreateLinkPersonGroupItem(UpdateJunctionBoxFistCreateLinkPersonGroupRequestData createLinkPersonGroupItem) {
    if (this.createLinkPersonGroup == null) {
      this.createLinkPersonGroup = new ArrayList<>();
    }
    this.createLinkPersonGroup.add(createLinkPersonGroupItem);
    return this;
  }

   /**
   * Get createLinkPersonGroup
   * @return createLinkPersonGroup
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATE_LINK_PERSON_GROUP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<UpdateJunctionBoxFistCreateLinkPersonGroupRequestData> getCreateLinkPersonGroup() {
    return createLinkPersonGroup;
  }


  @JsonProperty(JSON_PROPERTY_CREATE_LINK_PERSON_GROUP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreateLinkPersonGroup(List<UpdateJunctionBoxFistCreateLinkPersonGroupRequestData> createLinkPersonGroup) {
    this.createLinkPersonGroup = createLinkPersonGroup;
  }


  public UpdateJunctionBoxFistRequestData createLinkSite(List<UpdateJunctionBoxFistCreateLinkSiteRequestData> createLinkSite) {
    
    this.createLinkSite = createLinkSite;
    return this;
  }

  public UpdateJunctionBoxFistRequestData addCreateLinkSiteItem(UpdateJunctionBoxFistCreateLinkSiteRequestData createLinkSiteItem) {
    if (this.createLinkSite == null) {
      this.createLinkSite = new ArrayList<>();
    }
    this.createLinkSite.add(createLinkSiteItem);
    return this;
  }

   /**
   * Get createLinkSite
   * @return createLinkSite
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATE_LINK_SITE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<UpdateJunctionBoxFistCreateLinkSiteRequestData> getCreateLinkSite() {
    return createLinkSite;
  }


  @JsonProperty(JSON_PROPERTY_CREATE_LINK_SITE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreateLinkSite(List<UpdateJunctionBoxFistCreateLinkSiteRequestData> createLinkSite) {
    this.createLinkSite = createLinkSite;
  }


  public UpdateJunctionBoxFistRequestData deleteLinkContract(List<UpdateJunctionBoxFistDeleteLinkContractRequestData> deleteLinkContract) {
    
    this.deleteLinkContract = deleteLinkContract;
    return this;
  }

  public UpdateJunctionBoxFistRequestData addDeleteLinkContractItem(UpdateJunctionBoxFistDeleteLinkContractRequestData deleteLinkContractItem) {
    if (this.deleteLinkContract == null) {
      this.deleteLinkContract = new ArrayList<>();
    }
    this.deleteLinkContract.add(deleteLinkContractItem);
    return this;
  }

   /**
   * Get deleteLinkContract
   * @return deleteLinkContract
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELETE_LINK_CONTRACT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<UpdateJunctionBoxFistDeleteLinkContractRequestData> getDeleteLinkContract() {
    return deleteLinkContract;
  }


  @JsonProperty(JSON_PROPERTY_DELETE_LINK_CONTRACT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeleteLinkContract(List<UpdateJunctionBoxFistDeleteLinkContractRequestData> deleteLinkContract) {
    this.deleteLinkContract = deleteLinkContract;
  }


  public UpdateJunctionBoxFistRequestData deleteLinkFrameContract(List<UpdateJunctionBoxFistDeleteLinkFrameContractRequestData> deleteLinkFrameContract) {
    
    this.deleteLinkFrameContract = deleteLinkFrameContract;
    return this;
  }

  public UpdateJunctionBoxFistRequestData addDeleteLinkFrameContractItem(UpdateJunctionBoxFistDeleteLinkFrameContractRequestData deleteLinkFrameContractItem) {
    if (this.deleteLinkFrameContract == null) {
      this.deleteLinkFrameContract = new ArrayList<>();
    }
    this.deleteLinkFrameContract.add(deleteLinkFrameContractItem);
    return this;
  }

   /**
   * Get deleteLinkFrameContract
   * @return deleteLinkFrameContract
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELETE_LINK_FRAME_CONTRACT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<UpdateJunctionBoxFistDeleteLinkFrameContractRequestData> getDeleteLinkFrameContract() {
    return deleteLinkFrameContract;
  }


  @JsonProperty(JSON_PROPERTY_DELETE_LINK_FRAME_CONTRACT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeleteLinkFrameContract(List<UpdateJunctionBoxFistDeleteLinkFrameContractRequestData> deleteLinkFrameContract) {
    this.deleteLinkFrameContract = deleteLinkFrameContract;
  }


  public UpdateJunctionBoxFistRequestData deleteLinkMaintenanceContract(List<UpdateJunctionBoxFistDeleteLinkMaintenanceContractRequestData> deleteLinkMaintenanceContract) {
    
    this.deleteLinkMaintenanceContract = deleteLinkMaintenanceContract;
    return this;
  }

  public UpdateJunctionBoxFistRequestData addDeleteLinkMaintenanceContractItem(UpdateJunctionBoxFistDeleteLinkMaintenanceContractRequestData deleteLinkMaintenanceContractItem) {
    if (this.deleteLinkMaintenanceContract == null) {
      this.deleteLinkMaintenanceContract = new ArrayList<>();
    }
    this.deleteLinkMaintenanceContract.add(deleteLinkMaintenanceContractItem);
    return this;
  }

   /**
   * Get deleteLinkMaintenanceContract
   * @return deleteLinkMaintenanceContract
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELETE_LINK_MAINTENANCE_CONTRACT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<UpdateJunctionBoxFistDeleteLinkMaintenanceContractRequestData> getDeleteLinkMaintenanceContract() {
    return deleteLinkMaintenanceContract;
  }


  @JsonProperty(JSON_PROPERTY_DELETE_LINK_MAINTENANCE_CONTRACT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeleteLinkMaintenanceContract(List<UpdateJunctionBoxFistDeleteLinkMaintenanceContractRequestData> deleteLinkMaintenanceContract) {
    this.deleteLinkMaintenanceContract = deleteLinkMaintenanceContract;
  }


  public UpdateJunctionBoxFistRequestData deleteLinkOrganization(List<UpdateJunctionBoxFistDeleteLinkOrganizationRequestData> deleteLinkOrganization) {
    
    this.deleteLinkOrganization = deleteLinkOrganization;
    return this;
  }

  public UpdateJunctionBoxFistRequestData addDeleteLinkOrganizationItem(UpdateJunctionBoxFistDeleteLinkOrganizationRequestData deleteLinkOrganizationItem) {
    if (this.deleteLinkOrganization == null) {
      this.deleteLinkOrganization = new ArrayList<>();
    }
    this.deleteLinkOrganization.add(deleteLinkOrganizationItem);
    return this;
  }

   /**
   * Get deleteLinkOrganization
   * @return deleteLinkOrganization
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELETE_LINK_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<UpdateJunctionBoxFistDeleteLinkOrganizationRequestData> getDeleteLinkOrganization() {
    return deleteLinkOrganization;
  }


  @JsonProperty(JSON_PROPERTY_DELETE_LINK_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeleteLinkOrganization(List<UpdateJunctionBoxFistDeleteLinkOrganizationRequestData> deleteLinkOrganization) {
    this.deleteLinkOrganization = deleteLinkOrganization;
  }


  public UpdateJunctionBoxFistRequestData deleteLinkPerson(List<UpdateJunctionBoxFistDeleteLinkPersonRequestData> deleteLinkPerson) {
    
    this.deleteLinkPerson = deleteLinkPerson;
    return this;
  }

  public UpdateJunctionBoxFistRequestData addDeleteLinkPersonItem(UpdateJunctionBoxFistDeleteLinkPersonRequestData deleteLinkPersonItem) {
    if (this.deleteLinkPerson == null) {
      this.deleteLinkPerson = new ArrayList<>();
    }
    this.deleteLinkPerson.add(deleteLinkPersonItem);
    return this;
  }

   /**
   * Get deleteLinkPerson
   * @return deleteLinkPerson
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELETE_LINK_PERSON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<UpdateJunctionBoxFistDeleteLinkPersonRequestData> getDeleteLinkPerson() {
    return deleteLinkPerson;
  }


  @JsonProperty(JSON_PROPERTY_DELETE_LINK_PERSON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeleteLinkPerson(List<UpdateJunctionBoxFistDeleteLinkPersonRequestData> deleteLinkPerson) {
    this.deleteLinkPerson = deleteLinkPerson;
  }


  public UpdateJunctionBoxFistRequestData deleteLinkPersonGroup(List<UpdateJunctionBoxFistDeleteLinkPersonGroupRequestData> deleteLinkPersonGroup) {
    
    this.deleteLinkPersonGroup = deleteLinkPersonGroup;
    return this;
  }

  public UpdateJunctionBoxFistRequestData addDeleteLinkPersonGroupItem(UpdateJunctionBoxFistDeleteLinkPersonGroupRequestData deleteLinkPersonGroupItem) {
    if (this.deleteLinkPersonGroup == null) {
      this.deleteLinkPersonGroup = new ArrayList<>();
    }
    this.deleteLinkPersonGroup.add(deleteLinkPersonGroupItem);
    return this;
  }

   /**
   * Get deleteLinkPersonGroup
   * @return deleteLinkPersonGroup
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELETE_LINK_PERSON_GROUP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<UpdateJunctionBoxFistDeleteLinkPersonGroupRequestData> getDeleteLinkPersonGroup() {
    return deleteLinkPersonGroup;
  }


  @JsonProperty(JSON_PROPERTY_DELETE_LINK_PERSON_GROUP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeleteLinkPersonGroup(List<UpdateJunctionBoxFistDeleteLinkPersonGroupRequestData> deleteLinkPersonGroup) {
    this.deleteLinkPersonGroup = deleteLinkPersonGroup;
  }


  public UpdateJunctionBoxFistRequestData deleteLinkSite(List<UpdateJunctionBoxFistDeleteLinkSiteRequestData> deleteLinkSite) {
    
    this.deleteLinkSite = deleteLinkSite;
    return this;
  }

  public UpdateJunctionBoxFistRequestData addDeleteLinkSiteItem(UpdateJunctionBoxFistDeleteLinkSiteRequestData deleteLinkSiteItem) {
    if (this.deleteLinkSite == null) {
      this.deleteLinkSite = new ArrayList<>();
    }
    this.deleteLinkSite.add(deleteLinkSiteItem);
    return this;
  }

   /**
   * Get deleteLinkSite
   * @return deleteLinkSite
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELETE_LINK_SITE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<UpdateJunctionBoxFistDeleteLinkSiteRequestData> getDeleteLinkSite() {
    return deleteLinkSite;
  }


  @JsonProperty(JSON_PROPERTY_DELETE_LINK_SITE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeleteLinkSite(List<UpdateJunctionBoxFistDeleteLinkSiteRequestData> deleteLinkSite) {
    this.deleteLinkSite = deleteLinkSite;
  }


  public UpdateJunctionBoxFistRequestData installOperatingSystemInstallation(UpdateJunctionBoxFistInstallOperatingSystemInstallationRequestData installOperatingSystemInstallation) {
    
    this.installOperatingSystemInstallation = installOperatingSystemInstallation;
    return this;
  }

   /**
   * Get installOperatingSystemInstallation
   * @return installOperatingSystemInstallation
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INSTALL_OPERATING_SYSTEM_INSTALLATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UpdateJunctionBoxFistInstallOperatingSystemInstallationRequestData getInstallOperatingSystemInstallation() {
    return installOperatingSystemInstallation;
  }


  @JsonProperty(JSON_PROPERTY_INSTALL_OPERATING_SYSTEM_INSTALLATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInstallOperatingSystemInstallation(UpdateJunctionBoxFistInstallOperatingSystemInstallationRequestData installOperatingSystemInstallation) {
    this.installOperatingSystemInstallation = installOperatingSystemInstallation;
  }


  public UpdateJunctionBoxFistRequestData swapOperatingSystemInstallation(UpdateJunctionBoxFistSwapOperatingSystemInstallationRequestData swapOperatingSystemInstallation) {
    
    this.swapOperatingSystemInstallation = swapOperatingSystemInstallation;
    return this;
  }

   /**
   * Get swapOperatingSystemInstallation
   * @return swapOperatingSystemInstallation
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SWAP_OPERATING_SYSTEM_INSTALLATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UpdateJunctionBoxFistSwapOperatingSystemInstallationRequestData getSwapOperatingSystemInstallation() {
    return swapOperatingSystemInstallation;
  }


  @JsonProperty(JSON_PROPERTY_SWAP_OPERATING_SYSTEM_INSTALLATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSwapOperatingSystemInstallation(UpdateJunctionBoxFistSwapOperatingSystemInstallationRequestData swapOperatingSystemInstallation) {
    this.swapOperatingSystemInstallation = swapOperatingSystemInstallation;
  }


  public UpdateJunctionBoxFistRequestData updateLinkOrganization(List<UpdateJunctionBoxFistUpdateLinkOrganizationRequestData> updateLinkOrganization) {
    
    this.updateLinkOrganization = updateLinkOrganization;
    return this;
  }

  public UpdateJunctionBoxFistRequestData addUpdateLinkOrganizationItem(UpdateJunctionBoxFistUpdateLinkOrganizationRequestData updateLinkOrganizationItem) {
    if (this.updateLinkOrganization == null) {
      this.updateLinkOrganization = new ArrayList<>();
    }
    this.updateLinkOrganization.add(updateLinkOrganizationItem);
    return this;
  }

   /**
   * Get updateLinkOrganization
   * @return updateLinkOrganization
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATE_LINK_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<UpdateJunctionBoxFistUpdateLinkOrganizationRequestData> getUpdateLinkOrganization() {
    return updateLinkOrganization;
  }


  @JsonProperty(JSON_PROPERTY_UPDATE_LINK_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdateLinkOrganization(List<UpdateJunctionBoxFistUpdateLinkOrganizationRequestData> updateLinkOrganization) {
    this.updateLinkOrganization = updateLinkOrganization;
  }


  public UpdateJunctionBoxFistRequestData updateLinkPerson(List<UpdateJunctionBoxFistUpdateLinkPersonRequestData> updateLinkPerson) {
    
    this.updateLinkPerson = updateLinkPerson;
    return this;
  }

  public UpdateJunctionBoxFistRequestData addUpdateLinkPersonItem(UpdateJunctionBoxFistUpdateLinkPersonRequestData updateLinkPersonItem) {
    if (this.updateLinkPerson == null) {
      this.updateLinkPerson = new ArrayList<>();
    }
    this.updateLinkPerson.add(updateLinkPersonItem);
    return this;
  }

   /**
   * Get updateLinkPerson
   * @return updateLinkPerson
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATE_LINK_PERSON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<UpdateJunctionBoxFistUpdateLinkPersonRequestData> getUpdateLinkPerson() {
    return updateLinkPerson;
  }


  @JsonProperty(JSON_PROPERTY_UPDATE_LINK_PERSON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdateLinkPerson(List<UpdateJunctionBoxFistUpdateLinkPersonRequestData> updateLinkPerson) {
    this.updateLinkPerson = updateLinkPerson;
  }


  public UpdateJunctionBoxFistRequestData updateLinkPersonGroup(List<UpdateJunctionBoxFistUpdateLinkPersonGroupRequestData> updateLinkPersonGroup) {
    
    this.updateLinkPersonGroup = updateLinkPersonGroup;
    return this;
  }

  public UpdateJunctionBoxFistRequestData addUpdateLinkPersonGroupItem(UpdateJunctionBoxFistUpdateLinkPersonGroupRequestData updateLinkPersonGroupItem) {
    if (this.updateLinkPersonGroup == null) {
      this.updateLinkPersonGroup = new ArrayList<>();
    }
    this.updateLinkPersonGroup.add(updateLinkPersonGroupItem);
    return this;
  }

   /**
   * Get updateLinkPersonGroup
   * @return updateLinkPersonGroup
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATE_LINK_PERSON_GROUP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<UpdateJunctionBoxFistUpdateLinkPersonGroupRequestData> getUpdateLinkPersonGroup() {
    return updateLinkPersonGroup;
  }


  @JsonProperty(JSON_PROPERTY_UPDATE_LINK_PERSON_GROUP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdateLinkPersonGroup(List<UpdateJunctionBoxFistUpdateLinkPersonGroupRequestData> updateLinkPersonGroup) {
    this.updateLinkPersonGroup = updateLinkPersonGroup;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateJunctionBoxFistRequestData updateJunctionBoxFistRequestData = (UpdateJunctionBoxFistRequestData) o;
    return Objects.equals(this.sourceId, updateJunctionBoxFistRequestData.sourceId) &&
        Objects.equals(this.sourceSystem, updateJunctionBoxFistRequestData.sourceSystem) &&
        Objects.equals(this.contextId, updateJunctionBoxFistRequestData.contextId) &&
        Objects.equals(this.remark, updateJunctionBoxFistRequestData.remark) &&
        Objects.equals(this.visibleId, updateJunctionBoxFistRequestData.visibleId) &&
        Objects.equals(this.id, updateJunctionBoxFistRequestData.id) &&
        Objects.equals(this.serialNo, updateJunctionBoxFistRequestData.serialNo) &&
        Objects.equals(this.createLinkContract, updateJunctionBoxFistRequestData.createLinkContract) &&
        Objects.equals(this.createLinkFrameContract, updateJunctionBoxFistRequestData.createLinkFrameContract) &&
        Objects.equals(this.createLinkMaintenanceContract, updateJunctionBoxFistRequestData.createLinkMaintenanceContract) &&
        Objects.equals(this.createLinkOrganization, updateJunctionBoxFistRequestData.createLinkOrganization) &&
        Objects.equals(this.createLinkPerson, updateJunctionBoxFistRequestData.createLinkPerson) &&
        Objects.equals(this.createLinkPersonGroup, updateJunctionBoxFistRequestData.createLinkPersonGroup) &&
        Objects.equals(this.createLinkSite, updateJunctionBoxFistRequestData.createLinkSite) &&
        Objects.equals(this.deleteLinkContract, updateJunctionBoxFistRequestData.deleteLinkContract) &&
        Objects.equals(this.deleteLinkFrameContract, updateJunctionBoxFistRequestData.deleteLinkFrameContract) &&
        Objects.equals(this.deleteLinkMaintenanceContract, updateJunctionBoxFistRequestData.deleteLinkMaintenanceContract) &&
        Objects.equals(this.deleteLinkOrganization, updateJunctionBoxFistRequestData.deleteLinkOrganization) &&
        Objects.equals(this.deleteLinkPerson, updateJunctionBoxFistRequestData.deleteLinkPerson) &&
        Objects.equals(this.deleteLinkPersonGroup, updateJunctionBoxFistRequestData.deleteLinkPersonGroup) &&
        Objects.equals(this.deleteLinkSite, updateJunctionBoxFistRequestData.deleteLinkSite) &&
        Objects.equals(this.installOperatingSystemInstallation, updateJunctionBoxFistRequestData.installOperatingSystemInstallation) &&
        Objects.equals(this.swapOperatingSystemInstallation, updateJunctionBoxFistRequestData.swapOperatingSystemInstallation) &&
        Objects.equals(this.updateLinkOrganization, updateJunctionBoxFistRequestData.updateLinkOrganization) &&
        Objects.equals(this.updateLinkPerson, updateJunctionBoxFistRequestData.updateLinkPerson) &&
        Objects.equals(this.updateLinkPersonGroup, updateJunctionBoxFistRequestData.updateLinkPersonGroup);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sourceId, sourceSystem, contextId, remark, visibleId, id, serialNo, createLinkContract, createLinkFrameContract, createLinkMaintenanceContract, createLinkOrganization, createLinkPerson, createLinkPersonGroup, createLinkSite, deleteLinkContract, deleteLinkFrameContract, deleteLinkMaintenanceContract, deleteLinkOrganization, deleteLinkPerson, deleteLinkPersonGroup, deleteLinkSite, installOperatingSystemInstallation, swapOperatingSystemInstallation, updateLinkOrganization, updateLinkPerson, updateLinkPersonGroup);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateJunctionBoxFistRequestData {\n");
    sb.append("    sourceId: ").append(toIndentedString(sourceId)).append("\n");
    sb.append("    sourceSystem: ").append(toIndentedString(sourceSystem)).append("\n");
    sb.append("    contextId: ").append(toIndentedString(contextId)).append("\n");
    sb.append("    remark: ").append(toIndentedString(remark)).append("\n");
    sb.append("    visibleId: ").append(toIndentedString(visibleId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    serialNo: ").append(toIndentedString(serialNo)).append("\n");
    sb.append("    createLinkContract: ").append(toIndentedString(createLinkContract)).append("\n");
    sb.append("    createLinkFrameContract: ").append(toIndentedString(createLinkFrameContract)).append("\n");
    sb.append("    createLinkMaintenanceContract: ").append(toIndentedString(createLinkMaintenanceContract)).append("\n");
    sb.append("    createLinkOrganization: ").append(toIndentedString(createLinkOrganization)).append("\n");
    sb.append("    createLinkPerson: ").append(toIndentedString(createLinkPerson)).append("\n");
    sb.append("    createLinkPersonGroup: ").append(toIndentedString(createLinkPersonGroup)).append("\n");
    sb.append("    createLinkSite: ").append(toIndentedString(createLinkSite)).append("\n");
    sb.append("    deleteLinkContract: ").append(toIndentedString(deleteLinkContract)).append("\n");
    sb.append("    deleteLinkFrameContract: ").append(toIndentedString(deleteLinkFrameContract)).append("\n");
    sb.append("    deleteLinkMaintenanceContract: ").append(toIndentedString(deleteLinkMaintenanceContract)).append("\n");
    sb.append("    deleteLinkOrganization: ").append(toIndentedString(deleteLinkOrganization)).append("\n");
    sb.append("    deleteLinkPerson: ").append(toIndentedString(deleteLinkPerson)).append("\n");
    sb.append("    deleteLinkPersonGroup: ").append(toIndentedString(deleteLinkPersonGroup)).append("\n");
    sb.append("    deleteLinkSite: ").append(toIndentedString(deleteLinkSite)).append("\n");
    sb.append("    installOperatingSystemInstallation: ").append(toIndentedString(installOperatingSystemInstallation)).append("\n");
    sb.append("    swapOperatingSystemInstallation: ").append(toIndentedString(swapOperatingSystemInstallation)).append("\n");
    sb.append("    updateLinkOrganization: ").append(toIndentedString(updateLinkOrganization)).append("\n");
    sb.append("    updateLinkPerson: ").append(toIndentedString(updateLinkPerson)).append("\n");
    sb.append("    updateLinkPersonGroup: ").append(toIndentedString(updateLinkPersonGroup)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

