/*
 * Swagger for Command BGE
 * Swagger API for FNT Command Business Gateway
 *
 * The version of the OpenAPI document: 20240131110751
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fntsoftware.businessgateway.entities;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fntsoftware.businessgateway.entities.RestrictionsBoolean;
import com.fntsoftware.businessgateway.entities.RestrictionsNumeric;
import com.fntsoftware.businessgateway.entities.RestrictionsString;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * VirtualHardDiskQueryRestriction
 */
@JsonPropertyOrder({
  VirtualHardDiskQueryRestriction.JSON_PROPERTY_STORE_WITH_VM,
  VirtualHardDiskQueryRestriction.JSON_PROPERTY_C_FWTYPE,
  VirtualHardDiskQueryRestriction.JSON_PROPERTY_DATASOURCE,
  VirtualHardDiskQueryRestriction.JSON_PROPERTY_C_HOTSPARE,
  VirtualHardDiskQueryRestriction.JSON_PROPERTY_DATASOURCE_ID,
  VirtualHardDiskQueryRestriction.JSON_PROPERTY_NAME,
  VirtualHardDiskQueryRestriction.JSON_PROPERTY_HDD_MODE,
  VirtualHardDiskQueryRestriction.JSON_PROPERTY_V_MODE,
  VirtualHardDiskQueryRestriction.JSON_PROPERTY_ELID,
  VirtualHardDiskQueryRestriction.JSON_PROPERTY_C_PART_NO,
  VirtualHardDiskQueryRestriction.JSON_PROPERTY_FIRST,
  VirtualHardDiskQueryRestriction.JSON_PROPERTY_CAPACITY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-31T11:10:37.320689708Z[Etc/UTC]")
public class VirtualHardDiskQueryRestriction {
  public static final String JSON_PROPERTY_STORE_WITH_VM = "storeWithVm";
  private RestrictionsBoolean storeWithVm;

  public static final String JSON_PROPERTY_C_FWTYPE = "cFwtype";
  private RestrictionsString cFwtype;

  public static final String JSON_PROPERTY_DATASOURCE = "datasource";
  private RestrictionsString datasource;

  public static final String JSON_PROPERTY_C_HOTSPARE = "cHotspare";
  private RestrictionsString cHotspare;

  public static final String JSON_PROPERTY_DATASOURCE_ID = "datasourceId";
  private RestrictionsString datasourceId;

  public static final String JSON_PROPERTY_NAME = "name";
  private RestrictionsString name;

  public static final String JSON_PROPERTY_HDD_MODE = "hddMode";
  private RestrictionsString hddMode;

  public static final String JSON_PROPERTY_V_MODE = "vMode";
  private RestrictionsString vMode;

  public static final String JSON_PROPERTY_ELID = "elid";
  private RestrictionsString elid;

  public static final String JSON_PROPERTY_C_PART_NO = "cPartNo";
  private RestrictionsString cPartNo;

  public static final String JSON_PROPERTY_FIRST = "first";
  private RestrictionsNumeric first;

  public static final String JSON_PROPERTY_CAPACITY = "capacity";
  private RestrictionsNumeric capacity;

  public VirtualHardDiskQueryRestriction() {
  }

  public VirtualHardDiskQueryRestriction storeWithVm(RestrictionsBoolean storeWithVm) {
    
    this.storeWithVm = storeWithVm;
    return this;
  }

   /**
   * Get storeWithVm
   * @return storeWithVm
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STORE_WITH_VM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsBoolean getStoreWithVm() {
    return storeWithVm;
  }


  @JsonProperty(JSON_PROPERTY_STORE_WITH_VM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStoreWithVm(RestrictionsBoolean storeWithVm) {
    this.storeWithVm = storeWithVm;
  }


  public VirtualHardDiskQueryRestriction cFwtype(RestrictionsString cFwtype) {
    
    this.cFwtype = cFwtype;
    return this;
  }

   /**
   * Get cFwtype
   * @return cFwtype
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_C_FWTYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getcFwtype() {
    return cFwtype;
  }


  @JsonProperty(JSON_PROPERTY_C_FWTYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setcFwtype(RestrictionsString cFwtype) {
    this.cFwtype = cFwtype;
  }


  public VirtualHardDiskQueryRestriction datasource(RestrictionsString datasource) {
    
    this.datasource = datasource;
    return this;
  }

   /**
   * Get datasource
   * @return datasource
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATASOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getDatasource() {
    return datasource;
  }


  @JsonProperty(JSON_PROPERTY_DATASOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDatasource(RestrictionsString datasource) {
    this.datasource = datasource;
  }


  public VirtualHardDiskQueryRestriction cHotspare(RestrictionsString cHotspare) {
    
    this.cHotspare = cHotspare;
    return this;
  }

   /**
   * Get cHotspare
   * @return cHotspare
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_C_HOTSPARE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getcHotspare() {
    return cHotspare;
  }


  @JsonProperty(JSON_PROPERTY_C_HOTSPARE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setcHotspare(RestrictionsString cHotspare) {
    this.cHotspare = cHotspare;
  }


  public VirtualHardDiskQueryRestriction datasourceId(RestrictionsString datasourceId) {
    
    this.datasourceId = datasourceId;
    return this;
  }

   /**
   * Get datasourceId
   * @return datasourceId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATASOURCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getDatasourceId() {
    return datasourceId;
  }


  @JsonProperty(JSON_PROPERTY_DATASOURCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDatasourceId(RestrictionsString datasourceId) {
    this.datasourceId = datasourceId;
  }


  public VirtualHardDiskQueryRestriction name(RestrictionsString name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(RestrictionsString name) {
    this.name = name;
  }


  public VirtualHardDiskQueryRestriction hddMode(RestrictionsString hddMode) {
    
    this.hddMode = hddMode;
    return this;
  }

   /**
   * Get hddMode
   * @return hddMode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HDD_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getHddMode() {
    return hddMode;
  }


  @JsonProperty(JSON_PROPERTY_HDD_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHddMode(RestrictionsString hddMode) {
    this.hddMode = hddMode;
  }


  public VirtualHardDiskQueryRestriction vMode(RestrictionsString vMode) {
    
    this.vMode = vMode;
    return this;
  }

   /**
   * Get vMode
   * @return vMode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_V_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getvMode() {
    return vMode;
  }


  @JsonProperty(JSON_PROPERTY_V_MODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setvMode(RestrictionsString vMode) {
    this.vMode = vMode;
  }


  public VirtualHardDiskQueryRestriction elid(RestrictionsString elid) {
    
    this.elid = elid;
    return this;
  }

   /**
   * Get elid
   * @return elid
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getElid() {
    return elid;
  }


  @JsonProperty(JSON_PROPERTY_ELID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setElid(RestrictionsString elid) {
    this.elid = elid;
  }


  public VirtualHardDiskQueryRestriction cPartNo(RestrictionsString cPartNo) {
    
    this.cPartNo = cPartNo;
    return this;
  }

   /**
   * Get cPartNo
   * @return cPartNo
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_C_PART_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsString getcPartNo() {
    return cPartNo;
  }


  @JsonProperty(JSON_PROPERTY_C_PART_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setcPartNo(RestrictionsString cPartNo) {
    this.cPartNo = cPartNo;
  }


  public VirtualHardDiskQueryRestriction first(RestrictionsNumeric first) {
    
    this.first = first;
    return this;
  }

   /**
   * Get first
   * @return first
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FIRST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsNumeric getFirst() {
    return first;
  }


  @JsonProperty(JSON_PROPERTY_FIRST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFirst(RestrictionsNumeric first) {
    this.first = first;
  }


  public VirtualHardDiskQueryRestriction capacity(RestrictionsNumeric capacity) {
    
    this.capacity = capacity;
    return this;
  }

   /**
   * Get capacity
   * @return capacity
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CAPACITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RestrictionsNumeric getCapacity() {
    return capacity;
  }


  @JsonProperty(JSON_PROPERTY_CAPACITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCapacity(RestrictionsNumeric capacity) {
    this.capacity = capacity;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VirtualHardDiskQueryRestriction virtualHardDiskQueryRestriction = (VirtualHardDiskQueryRestriction) o;
    return Objects.equals(this.storeWithVm, virtualHardDiskQueryRestriction.storeWithVm) &&
        Objects.equals(this.cFwtype, virtualHardDiskQueryRestriction.cFwtype) &&
        Objects.equals(this.datasource, virtualHardDiskQueryRestriction.datasource) &&
        Objects.equals(this.cHotspare, virtualHardDiskQueryRestriction.cHotspare) &&
        Objects.equals(this.datasourceId, virtualHardDiskQueryRestriction.datasourceId) &&
        Objects.equals(this.name, virtualHardDiskQueryRestriction.name) &&
        Objects.equals(this.hddMode, virtualHardDiskQueryRestriction.hddMode) &&
        Objects.equals(this.vMode, virtualHardDiskQueryRestriction.vMode) &&
        Objects.equals(this.elid, virtualHardDiskQueryRestriction.elid) &&
        Objects.equals(this.cPartNo, virtualHardDiskQueryRestriction.cPartNo) &&
        Objects.equals(this.first, virtualHardDiskQueryRestriction.first) &&
        Objects.equals(this.capacity, virtualHardDiskQueryRestriction.capacity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(storeWithVm, cFwtype, datasource, cHotspare, datasourceId, name, hddMode, vMode, elid, cPartNo, first, capacity);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VirtualHardDiskQueryRestriction {\n");
    sb.append("    storeWithVm: ").append(toIndentedString(storeWithVm)).append("\n");
    sb.append("    cFwtype: ").append(toIndentedString(cFwtype)).append("\n");
    sb.append("    datasource: ").append(toIndentedString(datasource)).append("\n");
    sb.append("    cHotspare: ").append(toIndentedString(cHotspare)).append("\n");
    sb.append("    datasourceId: ").append(toIndentedString(datasourceId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    hddMode: ").append(toIndentedString(hddMode)).append("\n");
    sb.append("    vMode: ").append(toIndentedString(vMode)).append("\n");
    sb.append("    elid: ").append(toIndentedString(elid)).append("\n");
    sb.append("    cPartNo: ").append(toIndentedString(cPartNo)).append("\n");
    sb.append("    first: ").append(toIndentedString(first)).append("\n");
    sb.append("    capacity: ").append(toIndentedString(capacity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

