#!/usr/bin/env bash

inside_git_repo="$(git rev-parse --is-inside-work-tree 2>/dev/null)"
if [ ! "$inside_git_repo" ]; then
  git init -b main
fi

./bin/git/init-hooks

# pip config set global.trusted-host  "pypi.org files.pythonhosted.org pypi.python.org" --trusted-host=pypi.python.org --trusted-host=pypi.org --trusted-host=files.pythonhosted.org

cp -f ./.devcontainer/bash_aliases.sh ~/.bash_aliases
